### ISSUE TITLE
English words are included as forms of the German "ihm"

### ISSUE THREAD

**Issue by yolpsoftware** [tatuylonen/wiktextract#100]
https://kaikki.org/dictionary/German/meaning/i/ih/ihm.html#ihm-de-pron-2IqTfpXh

The first sense of the word "ihm" in German has two entries in its `form_of` property:

* "er", which is correct. "ihm" ("him") is Dative of "er" ("he").
* "him", which is wrong. "him" is an English word, not a German one.

The second sense has the same error with "it", which is not a German word.

It seems the error does not come from Wiktionary: https://en.wiktionary.org/wiki/ihm#German

**Comment by tatuylonen** [comment]
I'm inclined to say this should be fixed in Wiktionary.  I do have code that heuristically tries to determine whether a word or phrase is English, but especially for short words like this it could easily err and think that the word is English even if it is not.  I could look at the case when there are exactly two bases and the second looks like English and then treat it as a translation.  However, this is not foolproof. I'm hesitant to implement it unless these cases are fairly common, as it could also break other cases.

**Comment by kristian-clausal** [comment]
I've "fixed" some of the punctuation on Wiktionary itself (commas into semicolons) to conform with all other entries in the German pronoun table. The ambiguity seems to have simply arisen because two entries (ihm and dich) just had words on the wrong side of a semicolon, so I edited the entries a bit to conform how most of the others do it. Also makes the entries slightly cleaner.

**Comment by tatuylonen** [comment]
I made some further fixes that are somewhat related to this.  At least now the form_of values look correct for both German (probably due to Kristian's earlier changes) and Hunsrik (due to fixes I just did).  The most recent fixes should be reflected on https://kaikki.org in a couple of days.
