### ISSUE TITLE
Mistaken dot in some base forms

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#101]
This error seems to come from Wiktionary, for example here:
https://en.wiktionary.org/wiki/fui#Spanish
The sentence is finished with a dot ("First-person singular (yo) preterite indicative form of ir."), which causes the JSON to have an entry like `word : "ir."`. It would be nice if the dot would be removed automatically.

**Comment by Vuizur** [comment]
I looked a bit into it, I think maybe the right approach could be to remove the dot unless the page lies in a "Spanish Abbreviations" category or if the second to last character is uppercase. (I don't know if that covers all edge cases though).

**Comment by tatuylonen** [comment]
It already removes "." at the end of the base word, unless the page with "." exists.  In this case, page "ir." exists.  Theoretically I could look at whether the referenced page has the same language, but I don't easily have that information (the page may not have been parsed yet; I would need to load it from the cache and parse it separately and look for the language - doable but somewhat complicated).  Also, there would probably be pages referencing at least Translingual pages from other languages and I suspect other cross-language references too.

I'm inclined to say that the rare cases were the word with the trailing "." also exists in Wiktionary should probably be fixed in Wiktionary.  In this case the "." comes from a language-specific template (or Lua code).  There is no guarantee that all templates/Lua modules for a language behave in the same way in this respect.  I have no idea how common it is for "." to be added at the end in these cases.

I suppose I could add a table of the most common templates that add "." at the end of alt_of/form_of, but I currently have no idea how many cases there are that are not handled by the current test for the existence of the page with the trailing ".".

**Comment by Vuizur** [comment]
I thought about it a bit. I think the problem is the Spanish verb lua template. So the dot is being added for all inflected forms that begin with es-verb I think, like for example muero
`{{es-verb form of|person=first-person|number=singular|tense=present|mood=indicative|ending=ir|morir}}`
Other languages I tested don't add a dot as far as I could tell, so the template is pretty unique in that. So there would be the option to ask in the Wiktionary forum to remove the dot (I don't know the probability of success). 
I only think it might be cool to fix it here because "ir" is one of the most common verbs with many strange irregular inflections and an end user might not realise that he has to remove the dot (and he might break a handful of words like [this one](https://en.wiktionary.org/wiki/d%C3%B3lares_de_EE.UU.) with a naive approach).
Maybe another approach that might  maybe be easier to implement would be to remove the dot from all Spanish verbs (it is hard to think of a verb that could end with a dot, I don't think such a thing will exist).

**Comment by tatuylonen** [comment]
I just implemented and committed your proposed approach.  The change should be reflected on https://kaikki.org in a couple of days.

It now removes the dot at the end of the base form in alt-of/form-of if the language is Spanish and part-of-speech is Verb.  It is easy to add other languages and parts of speech if needed.

**Comment by Vuizur** [comment]
This looks great, thanks for fixing it! It seems to work well.
