### ISSUE TITLE
Missing form_of tags in some Portuguese words

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#105]
I think this is a problem sometimes when the gloss contains the string "third-person plural", "masculine singular" or "feminine singular".
Example words: minarem, mimiam, ornamentassem, otimizarão (third-person plural)
enxuto, impresso, pego (masculine singular)
finda, incluída (feminine singular)

PS: This project is super useful for my own open source projects, it really is great 👍

**Comment by tatuylonen** [comment]
These should now be fixed (but please let me know if you notice further issues).  I just committed the changes and they should be reflected on https://kaikki.org on Monday (unless something goes wrong with my update run).

The issues were due to some parenthesized pronoun list variant not recognized and Portuguese "short past participle" and "long past participle" not recognized.
 
Thanks for the good bug report!
