### ISSUE TITLE
Parsing of the Wiktionary page "seis" fails for some languages

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#113]
For some reason all data that should be in the Spanish section is instead added to Scots instead, which can be seen in the kaikki data: https://kaikki.org/dictionary/All%20languages%20combined/meaning/s/se/seis.html 
I looked a bit at the Wiktionary source, but couldn't find the reason.

PS: This project is really amazing 👍

**Comment by tatuylonen** [comment]
Parsing seems to fail because {{sco-third-person|...}} under Scots expand to invalid HTML, with unterminated &lt;span&gt;.  I had special code in handling a subtitle in the parser that doesn't close HTML tags (probably I've seen subtitles inside HTML somewhere).  I changed that code so that &lt;span&gt; tags are closed at subtitled.  With that change, this page now seems to parse correctly.  This will probably fix many (thousands?) similar errors on other pages - probably every page using that template is affected, and possibly other templates too.  The fix should be reflected on https://kaikki.org in a couple of days.

**Comment by Vuizur** [comment]
It works great now 👍 Thanks for fixing it!
