### ISSUE TITLE
Documentation Update - Windows

### ISSUE THREAD

**Issue by jdell64** [tatuylonen/wiktextract#114]
You probably know this, but I don't believe this runs on windows. That being said, I was able to get it to run using WSL (https://docs.microsoft.com/en-us/windows/wsl/about). It would be beyond the scope of this tool to go over how to install that, but it might be nice to point users to that?

**Comment by tatuylonen** [comment]
You are right that it doesn't work well on Windows (most importantly because I don't think python multiprocessing handles shared memory on Windows, which limits this to use one core, which is very slow).  There could be other issues too.  WSL could definitely be a good option.  I don't personally have any Windows machine so I can't easily test, and I've never used WSL.  If you or someone would be willing to update the documentation for that, I would be happy to merge a change.

**Comment by jdell64** [comment]
What would you want documented? 

I already had WSL enabled / installed, so I figured I'd try to just follow the Linux instructions, and I think they just worked as is.

**Comment by tatuylonen** [comment]
Sorry this had slipped my attention... Basically I'm unable to write the Windows documentation since I don't use Windows.  But if you would be willing to write short instructions (half a page to a page, perhaps), I would gladly include them in the README.md or a separate documentation file to help those who want to run it on Windows.  (That said, since the parallelism doesn't quite work on Windows, it would be very slow as far as I know.)  My wish for the documentation would be to target it for the non-super-technical linguist who would like to run this, describing what needs to be installed (with links to more verbose instructions) and other relevant information to get started.  Also a word or two on the limitations/caveats would probably be good.

**Comment by yacoder** [comment]
I've added docs on how to run tests on Windows using VS Code and native Python. All tests now pass and the tool works too (in single-thread mode).

But it's an interesting idea to try WSL, because the code currently uses some Python APIs which are only supported for "Unix", like `os.pread`. I wonder if those would work on WSL as-is, without the need to support special workaround for Windows. Maybe I'll try WSL too.

**Comment by kristian-clausal** [comment]
Now that the specific issue that there is not Windows documentation is a bit better, I'll close this issue. If something comes up with regards to Windows, people can make new issues.
