### ISSUE TITLE
Environment for running locally on test pages?

### ISSUE THREAD

**Issue by Manishearth** [tatuylonen/wiktextract#118]
I'd like to tweak this tool (and contribute back if desired¹), however it seems like it's kinda really hard to run this tool on just one file without having the full database for templates and such. I'd like to be able to take the wikitext for a _single_ entry and produce an accurate parsed JSON blob without having to do this for all entries. Currently doing so somewhat works, however the template/Lua stuff doesn't work.

It seems like https://kaikki.org/dictionary/rawdata.html has the Template/Lua data already. How should I proceed to run this code on a single page _as if_ it would work when running on the entire database?

 ¹ I want to correctly extract Chinese pronunciation data and dialectical map data. Happy to contribute back code when I have it working.

**Comment by tatuylonen** [comment]
The best way to debug it is to extract the pages into separate files and create a cache file of the templates&modules.
Basically, run:
wiktwords --cache wikt-cache --pages-dir pages --language Translingual --all --out temp.ignore enwiktionary-<date>-pages-articles.xml.bz2
(the --language and --out parameters are not necessary; it runs faster extracting just some minor language)

Then you can generate and debug individual pages as follows (in the wiktextract top-level directory):
./wiktwords --cache wikt-cache --all-languages --all --human-readable --out temp pages/Words/ho/house.txt
(i.e., page source is under pages/Words, with first two characters of the word used for the subdirectory name)

You may need to install wikitextprocessor and wiktextract first for development ("pip3 install -e ." in each directory).

I welcome contributions to fixing the Chinese pronunciations and synonyms.  The synonym code probably should go in linkages.py.  The pronunciation extraction is currently in parse_pronunciation() in page.py (the Chinese dialectal tables might best be handled as a completely separate implementation rather than mixing it into the already complex current function).  It might also make sense to move the pronunciation parsing to a separate file (e.g., a new file pronunciations.py).

**Comment by Manishearth** [comment]
Sounds good, thanks!
