### ISSUE TITLE
Unable to find all senses

### ISSUE THREAD

**Issue by meetDeveloper** [tatuylonen/wiktextract#123]
I searched for word bed in Wiktionary [here](https://en.wiktionary.org/wiki/bed).

Result shows:

![image](https://user-images.githubusercontent.com/32453612/156847024-43fc88dd-52b7-4d3e-86a9-8668d7207cf6.png)

But when searching in kaikki [here](https://kaikki.org/dictionary/English/meaning/b/be/bed.html), result does not have all senses.

Investigation shows that only child entries are present and parent entries are not present in senses. 

We are able to find sense _**A prepared spot in which to spend the night**_ but are unable to find 
1. **_A piece of furniture, usually flat and soft, on which to rest or sleep._** 
2. **_A place, or flat surface or layer, on which something else rests or is laid._**.

Can we add parent senses as senses and child senses as subsenses _i.e_ having subsenses as key in a sense which would either be empty or have child senses present. I found this example [here](https://api.linguarobot.io/language/v1/entries/en/bed) that has done the same

**Comment by kristian-clausal** [comment]
The problem here is that people use root-senses and subsenses a bit inconsistently. For example the entry for [mischief](https://en.wiktionary.org/wiki/Wiktionary:Subsenses) has as one of its root senses "Harm or injury", with subsenses that specify that it's harm or injury by an agent of some sort. But I think it's clear that "Harm or injury" is not in itself a sense of *mischief*, it's just the name of a category of subsenses. In fact, the above link for *mischief* is actually just a link to Wiktionary:Subsenses with 'mischief' as the example used, so this use of root-senses and subsenses seems to be the wiktionary standard.

From the pov of kaikki.org, it's damned if you do, damned if you don't: we can't tell when a root sense is actually meant to be a sense or a category, so we default to going with what seems to be the wiktionary standard. Either we leave senses out, or introduce new senses that are too general and do not fit the word.

In this specific case, I would change the entry for *bed* to be like this:

1. Something to rest or sleep on.
    1. A piece of furniture, usually flat and soft, on which to rest on. [...]
    2. A prepared spot on which to spend the night [...]
    3. [...]
2. Flat place or surface on which to rest or lay...

**Comment by tatuylonen** [comment]
Is some action still needed on this?  As far as I can tell, both the parent sense and the more detailed sense are included in the "glosses" list (which contains two strings in these cases).  As noted by Kristian, it is very difficult to determine whether the parent sense should be interpreted as a separate sense or as a broader sense covering all of its subsenses (in the vast majority of cases it seems to be a broader sense grouping).

**Comment by meetDeveloper** [comment]
@tatuylonen @kristian-clausal Will it be possible to consider parent sense as grouping child sense as you said is the case in majority of cases.
