### ISSUE TITLE
Missing senses

### ISSUE THREAD

**Issue by jsannemo** [tatuylonen/wiktextract#128]
There are no senses extracted for https://en.wiktionary.org/wiki/%D1%82%D1%80%D0%B0%D0%BC%D0%B2%D0%B0%D0%B9#Russian

See e.g.
https://kaikki.org/dictionary/Russian/meaning/%D1%82/%D1%82%D1%80/%D1%82%D1%80%D0%B0%D0%BC%D0%B2%D0%B0%D0%B9.html

I can't see right away why this is the case, the page looks normal to me.

**Comment by kristian-clausal** [comment]
I think the entry has bad template use with {{sense|US}} and {{sense|UK}}. That's not what {{sense}} is for. Thing is, none of the others (qualifier and label) work either, because templates are used to specify the meaning of the sense or headword, not to specify what something means inside of a gloss.

I'm just gonna be rough and combine it all into one sense. It makes no sense to have them separate.

**Comment by kristian-clausal** [comment]
After some grepping through the wiktionary source, there's about 60~70 instances of {{sense|UK}} or  {{sense|US}} on wiktionary, which is nothing. I think we can safely assume that {{sense|Commonwealth}} and similar are much, much less common. It wouldn't be impossible to go through every article with these and correct them, except that in some instances it's just difficult to come up with anything to replace the {{sense}} with that gives a similar kind of output. The example in the above posts (tramway etc.) was simple, but others are a bit more complex and "justifiable".

**Comment by tatuylonen** [comment]
I just checked and at least for трамвай/Russian this issue now seems to be fixed (the sense is correctly extracted).  Are some additional fixes needed in the code?

(The fix is not yet reflected on https://kaikki.org, but should be tomorrow - I've had issues with the 20220401 dump extraction hanging, but I fixed that issue earlier today so hopefully the web site should update tonight)
