### ISSUE TITLE
Wrong canonical_form for учиться

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#130]
For the word учиться the canonical form mistakenly includes some grammatical information, so the following is detected (instead of simply учи́ться)
`forms": [
    {
      "form": "учи́ться impf - reflexive and passive verb for учи́ть",
      "tags": [
        "canonical"
      ]
    },`

**Comment by kristian-clausal** [comment]
An anonymous IP (wasn't me) seems to have fixed the wonky syntax on wiktionary recently, which _should_ fix the issue.  We will know when the next update that uses the most recent wiktionary source arrives. But yeah, if anyone sees issues like this, please consider whether "irregular" human-written content on the Wiktionary side could be replaced by a standard template. Sometimes it's not possible, because the templates can't handle everything unless programmed to--in which case you end up with weird stuff--but most of the time if you see anything formatted using manual formatting you can replace it with a template.

**Comment by Vuizur** [comment]
Sounds good! I hadn't considered this, you are totally right. I'll keep it in mind.

**Comment by tatuylonen** [comment]
Is this now resolved and can this issue be closed? Or is some action still needed?

**Comment by Vuizur** [comment]
Yup, I just checked and it is correct now in the newest version 👍👍
