### ISSUE TITLE
10 000 most common English words

### ISSUE THREAD

**Issue by acmpo6ou** [tatuylonen/wiktextract#136]
Hi!

I'd like to make an android app that would use Wiktionary, however downloading all the words from your side results in a 1,7 GB json file. Can I somehow download only the first 10K of most frequently used words?
There is a [link](https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists) that lists words by frequency.

Thanks!

**Comment by kristian-clausal** [comment]
Iirc, there is no frequency data in the wiktionary or wiktextract data, so you'd have to find the words using just the kind of frequency list that you've pointed to. Doing that, as long as you have a usable list of targets, should be pretty easy using the json data.

The json data the raw and processed extracts are actually a bunch of json objects one after another on separate lines, separated by \n. You can read the lines one by one and get a valid JSON object (that would usually be a single file) with the data for a single word. So, as long as you have a way to scan the lines (with the programming language of your choice) to find the appropriate fields fitlering them with a list of words, you should be able to pull out the word data for each word you wanted pretty easily and then output them in a .jsonl file or separate .json files for each object.

Unfortunately, "word" is a field that is used in other contexts than just "the word of this json object", so grepping wasn't helpful when I tried it just now. You have to read each line of the json data file, parse the json object on each line, and then filter by checking the "word" key in the root object.

```python
"""frequency-extract.py"""
import os
import json
import sys

if len(sys.argv) == 3:
    frequency_list = sys.argv[1]
    json_data = sys.argv[2]
else:
    print("python frequency-extract.py frequency_file json_data_file")
    quit()

with open(json_data, buffering=16*1024*1024) as jsonf, open(frequency_list) as freqf:
    
    targets = set(l.strip() for l in freqf)
    # Take the list of most frequent words, remove \n line breaks and remove
    # duplicates by making a python set.
    #print(targets)
    
    for line in jsonf:
        word = json.loads(line)
        #print(word["word"])
        if word["word"] in targets:
            print(json.dumps(word, sort_keys=True, ensure_ascii=False))
                    # Output json data into stdout. ensure_ascii=False turns off
                    # escaping Unicode characters so it's a bit prettier.
                    # Pipe this into destination file.
            #print(word["word"])
```

Download the json data file at the bottom of https://kaikki.org/dictionary/English/index.html, make a text file with all the words you want to find on separate lines, then run the above script with those files as the arguments.

The result is about 74 megs for the 1000 most common words data I downloaded off somewhere, so there are a lot of "duplicate" entries, but that's because frequency word lists are only concerned with raw text data and not the *meaning* of words (which wiktionary and we are).
