### ISSUE TITLE
No gloss extracted after category (medical)

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#141]
The affected word is [spálenina](https://en.wiktionary.org/wiki/sp%C3%A1lenina). It has [no gloss](https://kaikki.org/dictionary/All%20languages%20combined/meaning/s/sp/sp%C3%A1lenina.html) in the extracted info, unfortunately. I looked at the Wiktionary Wikitext but could not see any mistakes there at first glance.

**Comment by kristian-clausal** [comment]
That is weird. Trying out with a temporary file with different changes, this seems to be caused by the {{sense|medical}}. Either this is some really obscure on-off bug with the sense tag's output in combination with [[burn]], or there are a lot of {{s}} templates that we're breaking out there. Tatu will need to take a look at this.

**Comment by kristian-clausal** [comment]
Forgot to comment as we went through a few issues yesterday, but this should not be corrected. The issue was a kludgy regex expression that was meant to be used to ignore long lists of numbered example sentences ([for example iacebam](https://en.wiktionary.org/wiki/iacebam)), but it also caught things with a colon, which included basically all {{s}} templates. Should now be fixed, and updated on the website today or tomorrow.

**Comment by Vuizur** [comment]
Awesome, thanks 👍
