### ISSUE TITLE
[error] derived terms and extensions are assigned to the wrong sense

### ISSUE THREAD

**Issue by alexchandel** [tatuylonen/wiktextract#150]
Reconstructed entries often have multiple senses, like Proto-Indo-European's [(s)ker-](https://en.wiktionary.org/wiki/Reconstruction:Proto-Indo-European/(s)ker-).  Wiktextract incorrectly assigns all derived terms and extensions to the first sense, and nothing to the second sense.  It also mixes up the sense `id`s.

(Note that these separate senses are correctly emitted as separate lines in the JSONL.)

**Comment by jmviz** [comment]
I looked into this. The page [version](https://en.wiktionary.org/w/index.php?title=Reconstruction:Proto-Indo-European/(s)ker-&oldid=68495619) you linked has an idiosyncratic structure, where the etymology is placed below the level of the part of speech. Usually, by [wiktionary's entry layout guidelines](https://en.wiktionary.org/wiki/Wiktionary:Entry_layout#Etymology), it's the other way around:  etymology is a level 3 section (i.e. `===Etymology===`) and part of speech is level 4 (i.e. `====Root====`). Wiktextract actually insists on the conventional structure and if it finds otherwise will actually reorder the sections of the page to achieve it (see `fix_subtitle_hierarchy()` in `page.py`). 

I believe this improper section nesting is what gave wiktextract troubles. I changed the page so that the etymologies are above the parts of speech, in line with the structure of e.g. [ḱley-](https://en.wiktionary.org/wiki/Reconstruction:Proto-Indo-European/%E1%B8%B1ley-) and [dʰew-](https://en.wiktionary.org/wiki/Reconstruction:Proto-Indo-European/d%CA%B0ew-). I tested it locally and it now processes correctly.
