### ISSUE TITLE
FC Que

### ISSUE THREAD

**Issue by Sixque** [tatuylonen/wiktextract#156]
If I wanted to position the data in such away that it could be ported over into flashcards, how would I go about that? 

Format: The quick brown fox {TAB} jumps over the lazy dog.\r\n
Format: Word {TAB} Definition.\r\n

Additionally if not feasible, I'd settle for one contained text file that I could just Regex through. Any help would be greatly appreciated.

**Comment by kristian-clausal** [comment]
Unfortunately our data is not regexable, at the very least because certain keywords like "word" are reused as keys in different places in the data.

Additionally, the data is not flashcard-ready. Each json word entry contains a bunch of senses, and you would have to pick which one to use for each card specifically (or just use words that have only one sense on wiktionary). There *is* no one definition, usually, just like in a normal dictionary. Flash cards, if I've understood them correctly, take word definitions and try to condense them into the smallest meaningful explanation or translation they can and using straight-up uncurated wiktionary data would be a really bad flashcard system, because you'd have a ton of really rather useless text that a language learner doesn't and shouldn't care about yet.

If you want to use the data for curation, though, you have to use some programming to go through the .json. We use python, and the json package, so it's pretty simple to load the files we use and then go through the dicts we extract from each separate line to find what we need with a recursive search, or just accessing the data directly if we know where it is.

When the json is loaded into python memory, it does it pretty straightforwardly by just putting dicts and lists inside a root dict, one-to-one with the json structure. [This is a mapping of all the possible fields of a word entry](https://kaikki.org/dictionary/errors/mapping/index.html). You can use it to find where the data lies. If you want all the senses of a word, those are found as separate entries inside a list under "senses", a child of the root node.

In issue #136 I made someone a quick and simple python script to extract words from one of our files based on a list of words to be extracted. You can use that script as the basis of extracting data by modifying the last block inside the for loop that goes through each line.
