### ISSUE TITLE
Missing hyphenation data

### ISSUE THREAD

**Issue by gd4c** [tatuylonen/wiktextract#159]
For example, see under Pronunciation in https://en.wiktionary.org/wiki/during

**Comment by kristian-clausal** [comment]
Woops, turned out this was a bug and not a missing feature. The issue was with a long block of different regex tests, where the test for hyphenation was found after some more general tests that would greedily capture the flow. This has now been fixed, and hyphenations now appear inside the "sound" category.

**Comment by gd4c** [comment]
Thanks
