### ISSUE TITLE
No form_of tags for some Latin inflections

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#163]
Some latin words currently don't have the form_of tag, probably because they contain a string like "indicative/imperative" or "present/perfect" in the grammar specification. An example word would be putrefitis. More examples can be found [this dictionary here](https://raw.githubusercontent.com/Vuizur/Wiktionary-Dictionaries/2c9585a7c3b75b6c04fc540a5e9920f122e8108b/Latin-English%20Wiktionary%20dictionary.tsv), one only has to search for grammar terms like "plural" or "singular". (All forms with form_of tags should have been filtered out before.)

**Comment by kristian-clausal** [comment]
I've been taking a look at this and I have a kludge I'm trying to cobble together for the "indicative/imperative" style problem, but we'll see how it goes.

There's also other form-ofs in your data that are caused because of hierarchical subsenses not inheriting "form-ofness" from their higher levels, but that's a different kettle of fish for another day.

**Comment by kristian-clausal** [comment]
I think I've finally kludged something together.

Originally I had a more elaborate thing in form_descriptions/decode_tags going on, where I separated the string to the passed through into groups of outside text and indicative/imperative/conditional style alternatives, that I then combined into every possible combination, then pushing them forwards in the same place where the code previously separated the string... Only to find out all the combinations were all flattened anyhow into one long tag string, so it was unnecessary all around.

Try \#2 was to simply substitute all "/" with spaces, but that didn't work because we do have some legitimate entries in xlat_tags_map like "first/third-person" that will break by doing that. Eventually, it just loops through the words in the string, checks whether the entry is in xlat_tags_map, and if not and there's a "/" just split the word on it and append it without sanitation and pray to the winds to take it where it should be.

I am pretty sure this is strictly better than what we had before. Entries in xlat_tags_maps get through without alteration, words *not* in xlat_tags_maps would have given an error in any case, and splitting them in hopes of getting valid stuff downstream can't be worse and (almost always?) is better.

The issue I mentioned previously of hierarchical entries being broken seems to be corrected too. Can't find any of the brief examples I looked at previously because I think Vuizur's data has been changed since then, though, so leaving things open for now.

**Comment by Vuizur** [comment]
Sounds great!

My previous code had the bug that it did not ignore some inflections which should have been ignored (because they were not really inflections), which led to some false inherited inflections. So far only the Latin dictionary I linked has been re-generated with the corrected code, so the other files in my repo are still affected.
