### ISSUE TITLE
Articles parsed as declensions for German multiword terms

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#171]
Thanks for fixing the other issue already in record time 👍.

I noticed that for German multiword terms the articles get parsed as declensions. Examples are[ eulersche Formel](https://kaikki.org/dictionary/All%20languages%20combined/meaning/e/eu/eulersche%20Formel.html) and [vierblättriges Kleeblatt](https://kaikki.org/dictionary/All%20languages%20combined/meaning/v/vi/vierbl%C3%A4ttriges%20Kleeblatt.html).

**Comment by kristian-clausal** [comment]
I see the editors for German entries have found *yet another way* to express articles in content... *sigh*. These are weird enough that they'll have to be on the backburner for now.

**Comment by kristian-clausal** [comment]
I've just committed a horrible kludge for this, because the *other* kludge to remove German articles in their own cells was not enough.

lang_specific now has the possibility of a language having conditionally_ignored_cells, which is a dict of tag-keys with their own specific lists of word forms to ignore if they're detected in a table. However, a form is not skipped if the form has in its tags also the tag-key of the list (like "definite": ["die", "der" ...]), or if the the word of the article is also in the list of ignorable forms ; in which case you're looking at the article for "die" or "der" and don't want to skip, or you're looking at a table in the article for "der" that has the form "die" and don't want to skip because it's the article for an article.
