### ISSUE TITLE
Russian dump response is truncated before finishing

### ISSUE THREAD

**Issue by digitalheir** [tatuylonen/wiktextract#173]
I download https://kaikki.org/dictionary/Russian/kaikki.org-dictionary-Russian.json

Last line is not valid JSON:

`> awk 'NR==27543' kaikki.org-dictionary-Russian.json`

```
{"pos": "verb", "head_templates": [{"name": "ru-verb", "args": {"1": "\u043f\u043e\u043a\u0440\u044b\u0301\u0442\u044c", "2": "pf", "impf": "\u043a\u0440\u044b\u0442\u044c", "impf2": "\u043f\u043e\u043a\u0440\u044b\u0432\u0430\u0301\u0442\u044c"}, "expansion": "\u043f\u043e\u043a\u0440\u044b\u0301\u0442\u044c \u2022 (pokr\u00fd
```

What is the problem? Is my internet too slow and your server cuts connection with my computer, or is the file invalid?

**Comment by digitalheir** [comment]
Ah, indeed it seems to be that the server drops cx after every 60 seconds. I retried with `wget`, which automatically resumes download. Curious, but understandable. Was it intended behaviour?

**Comment by digitalheir** [comment]
Perhaps it would be nice to just print Cyrillic text literally, because escaping to JSON encoding really inflates the file by a lot, compare with https://github.com/tatuylonen/wiktextract/pull/18

**Comment by kristian-clausal** [comment]
I don't know much about the server side stuff like the cutoff, but the escaped utf-8 code in the .json is because the files are generated in the kaikki.org code and not wiktextract or wikitextprocessor, and it does so without the `enable_ascii=False` parameter. Then it's encoded as utf-8 with .encoded("utf8"), but the code where this is done was committed to the kaikki repo in June 2021, when that pull request above is from May 2021, so I'm reasonably certain the public-facing kaikki.org output is on purpose done like that, maybe for the most wide compatibility. @tatuylonen would have to answer this further.

**Comment by digitalheir** [comment]
@tatuylonen is it worth it to generate dumps in UTF-8 as well as ASCII? It might cut your server egress by ~<6 times for these non-ASCII script languages if `\uXXXX` is reduced to `x`.

**Comment by 1over137** [comment]
All JSON decoders are required to support UTF-8. I don't think there are any compatibility advantages to using ASCII escapes these days.

**Comment by kristian-clausal** [comment]
Woops, seems everyone here at the office thought either this was already done or that it was done on purpose. Some of the json.dumps() calls had `ensure_ascii=False`, some didn't. This has now been corrected on kaikki.org, so now downloads should have utf-8!
