### ISSUE TITLE
Bullet character is included at the end of "canonical" forms that have transliterations

### ISSUE THREAD

**Issue by jmviz** [tatuylonen/wiktextract#176]
For many languages, the head template(s) for a given word PoS entry expand to the word in the standard script, and the transliteration, with a bullet in between. For example, for Ancient Greek [στάδιος](https://en.wiktionary.org/wiki/%CF%83%CF%84%CE%AC%CE%B4%CE%B9%CE%BF%CF%82#Ancient_Greek), the head template expansion starts out: "στᾰ́δῐος [•](https://en.wiktionary.org/wiki/Wiktionary:Ancient_Greek_transliteration) (stádios)". The bullet actually contains a link to the explanation page for Ancient Greek transliteration. 

The first form recorded by [wiktextract](https://kaikki.org/dictionary/Ancient%20Greek/meaning/%CF%83/%CF%83%CF%84/%CF%83%CF%84%CE%AC%CE%B4%CE%B9%CE%BF%CF%82.html) is 

```json
{
      "form": "στᾰ́δῐος •",
      "tags": [
        "canonical",
        "masculine"
      ]
}
```

where the `"form"` value should of course instead be `"στᾰ́δῐος"`. The extra trailing bullet seems to happen for the canonical form for pretty much any language that includes a transliteration like this, as far as I can tell. Here are a couple other random examples for reference: 

https://en.wiktionary.org/wiki/%D7%93%D7%A8%D7%99%D7%99%D7%A2%D7%9F#Yiddish
https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D7%93/%D7%93%D7%A8/%D7%93%D7%A8%D7%99%D7%99%D7%A2%D7%9F.html

https://en.wiktionary.org/wiki/%D8%A3%D8%A8%D9%84%D8%B9
https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D8%A3/%D8%A3%D8%A8/%D8%A3%D8%A8%D9%84%D8%B9.html

**Comment by kristian-clausal** [comment]
Thankfully a simple fix, as long as you know where to actually put it...

Because the heads were handled properly otherwise (and we're not using the bullet for anything else), I'm just going to remove the spaces before a bullet and anything afterwards with a simple regex in form_descriptions/parse_word_heads() where other cleaning is also taking place. The regex shouldn't capture anything inappropriate like the article for "•"... Actually let me check that. Yeah, seems fine. It will catch anything that starts with whitespace and then a •, but that seems *really* unlikely. The unicode bullet is also not a 'natural' fit as punctuation. It *should* be fine.
