### ISSUE TITLE
Reconstruction language pages are no longer processed, even when requested with wiktwords --language parameter

### ISSUE THREAD

**Issue by jmviz** [tatuylonen/wiktextract#177]
Wiktextract no longer processes any pages in the `Reconstruction:` namespace. At first I thought this might be intentional for some reason. However, now I'm wondering if this was inadvertently done within the last some weeks, perhaps during the changes to how the config data is stored/structured and the revamping of the `wiktwords` script. I've come to think this may have been inadvertent because:

- All of the code that deals specifically with handling `Reconstruction` pages is still extant (e.g. in `page.py`).
- All `Reconstruction` languages are still present in `data/en/languages.json`.
- Even specifically requesting a reconstruction language to be processed by the `wiktwords` script (e.g. `--language ine-pro`) yields no entries for that language.
- No git commits in the last few months that I can see mention anything about `Reconstruction` languages.

Simply adding the line `ctx.NAMESPACE_DATA.get("Reconstruction", {}).get("name"),` to the definition of `RECOGNIZED_PREFIXES` in `wiktwords` is enough to reinstate processing of `Reconstruction` pages, although there is maybe a more principled fix depending on what the error was (if this was indeed unintentional).

**Comment by kristian-clausal** [comment]
RECOGNIZED_PREFIXES was introduced with xxyzz Chinese wiktionary additions, most probably just a way to introduce localization (like everything else in those commits), so this just seems like an oversight. Running wiktwords in one-page mode seems to bypass the issue (because you're manually giving it the page file to process, I assume), but the main cache-generation and batches probably rely on it to decide what to process and what to not process.

Currently regenerating the cache with the change, will unlock if something does turn up, but it's unlikely.

**Comment by xxyzz** [comment]
I just rename that variable to upper case and load the values from JSON file. Reconstruction namespace was not in that set before: https://github.com/tatuylonen/wiktextract/commit/69f230772b881b5da1d6a49e04b39772853a75f2#diff-838ad0a641f44893e4f8c35ff6e35d9c6f8737d1f1fe38528c5f22c3581a0b87L38-L39
