### ISSUE TITLE
Some Czech words have incorrect canonical form with the category appended

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#181]
Affected are for example the words Glum, Himálaj or Hlava XXII. What they all share is that they don't have any other forms or inflections.

The incorrect canonical forms look like this:
```Affected are for example
 "forms": [
    {
      "form": "Hlava XXIICategory:cs:American fiction",
      "head_nr": 1,
      "tags": [
        "canonical"
      ]
    }
  ],
```

Keep up the good work with this great project! :)

**Comment by kristian-clausal** [comment]
Yeah, I have kludged together something for this.

The issue is that our head parsing eats too much, even after subgloss lists, and when an article ends with a PoS-section and the category links are after it without the section "terminating", then the text of the Category: template-link is eaten by the head parsing. Because this makes the head parse as a really weird string, it is 1) assigned as the `canonical` form because it is different from the article title word and, happily 2) also flagged with a debug message that this `canonical` form looks weird.

The kludge is simply that strings starting with "Category:" are now filtered out. I just had an idea for a minor improvement; really, strings that start with "Category:" should mark that the Part of Speech section should be terminated, they shouldn't just be filtered out.

**Comment by kristian-clausal** [comment]
Part-of-speech sections are now being terminated when encountering a `[[Category:...]]`-link; these should only appear at the end of a language sections or page, so we know there shouldn't be anything to parse for PoS there.

**Comment by Vuizur** [comment]
That was fast, thank you!
