### ISSUE TITLE
"Multiplicative adverbs" table gets parsed as canonical form

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#185]
An example are the words like пятью or the similar adverbs like this: https://en.wiktionary.org/wiki/%D1%87%D0%B5%D1%82%D1%8B%D1%80%D0%BD%D0%B0%D0%B4%D1%86%D0%B0%D1%82%D1%8C%D1%8E

In the extracted data the table contents are parsed as canonical forms: https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%BF/%D0%BF%D1%8F/%D0%BF%D1%8F%D1%82%D1%8C%D1%8E.html

It is probably not the most important problem though 😀.

**Comment by kristian-clausal** [comment]
This is probably new, from the new code that attempts to split head sections so that even articles with multiple heads separated by multiple lists of senses would parse. But currently the code doesn't (can't) tell whether a template is actually a head template or something completely different.

I guess the templates could be expanded, but that's its own kettle of fish; costly and I think there might be side-effects.

**Comment by kristian-clausal** [comment]
This is totally going to break *something*, but [needs must](https://en.wiktionary.org/wiki/needs_must).

If a "head" candidate is not followed by any sense lists anywhere in the section, stop parsing heads at that point. The only exception, out of necessity, is the first head, which is always parsed even without a list of senses following. In any case, if this happens output a debug message so that I can see the damage later.
