### ISSUE TITLE
Phrases split by comma get parsed as multiple canonical forms

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#186]
An example is "while there's life, there's hope". This gets processed as having the canonical forms "while there's life" and "there's hope".

A solution might be to not use the comma to parse different canonical forms if the word is in a "proverbs" or "phrases" category. But no idea how hard this would be to implement.

**Comment by kristian-clausal** [comment]
Put some kludges to hopefully fix this.

Problem was with regexes (in two different places, with the second issue popping up after I fixed the splitting issue), which look really delicate and long, used to separate the head into logical parseable chunks. Of course part of this is splitting on commas. Currently, the code checks if ctx.title (the word or phrase of the article) contains commas, and then separates and preserves that in a minor preprocessing step.

That created another issue slightly downriver in the code, also with a regex, except this regex split just caused problems by basically stripping the commas away, creating a new canonical form like "while there's life there's hope" without commas. This was also kludged by checking whether there's a comma in ctx.title and then just throwing that into add_related instead of the regex-split stuff. That parameter that is sent to add_related is immediately reconstituted with " ".join *anyhow*, so there really is not much of a chance of things going wrong here.
