### ISSUE TITLE
Tags/labels with spaces are split

### ISSUE THREAD

**Issue by hcholm** [tatuylonen/wiktextract#188]
E.g. 'troll' in Polish on https://en.wiktionary.org/wiki/troll has "{{lb|pl|colloquial|Internet slang}}", which becomes "Tags: Internet, animate, colloquial, masculine, slang" on https://kaikki.org/dictionary/Polish/meaning/t/tr/troll.html .

**Comment by kristian-clausal** [comment]
Added "Internet slang" as an entry in xlat_tags_map. Because "Internet" and "slang" are separately parsed phrases already, it's impossible to create a system that would join them together as some third kind of tag instead without actually giving the parser the data to do it. This is actually the case for *all* parsed words and phrases (well, almost all, there are very few on-the-fly ones that Tatu has been able to make), so the solution is just to make "Internet slang" map to something, in this case the tag ["Internet"].
