### ISSUE TITLE
Missing sense in translations on "quadratic"

### ISSUE THREAD

**Issue by jacopofar** [tatuylonen/wiktextract#189]
Hello, and  thanks for the amazing project!

I am trying to build a JSON schema for the definitions, and doing so I found that the word "quadratic" has translations missing a sense.

From the definition at https://en.wiktionary.org/wiki/quadratic and the corresponding JSON I guess the problem comes from the character `²` in the sense template, but it's just a wild guess

**Comment by kristian-clausal** [comment]
It's actually not the ²'s that are the problem (though they could have easily been, interpreted as footnotes or similar), it's the `=` equal sign. Our template parsing code only emulates the underlying code of Wikitext, and a bit wrong in places because Tatu did it originally as a black box without delving too deep into the PHP and Lua stuff. Looking at all of that is currently in the pipeline, so this might get fixed by itself eventually.

**Comment by jacopofar** [comment]
Thanks! I found a few other cases but they were missing senses already in Witktionary itself, and I'm fixing the pages directly

**Comment by kristian-clausal** [comment]
https://github.com/tatuylonen/wiktextract/commit/f2a669441996362baf05540768df09263fe7223f

Not a "fix", I haven't actually fixed the emulation of Wiktionary parsing, but an ugly, ugly kludge.

The issue was ultimately that the = equal sign was passed onwards as an argument, {{{1}}}, which was then misparsed down the line when it was expanded inside and #invoke call (links|remove_link), which cut the whole parameter in half:
{"of a class of polynomial of the form y": "ax² + bx + c"}, and when remove_link() saw that "text" was a Lua table (named list of parameters) it tried to access the table's "1"-key (in Lua, all arrays, lists etc. are combined into a single hash map type) didn't find anything because there was only one parameter called "of a class...", and then returned nothing.

The kludge: when expanding an argument, if there's a = that is outside of `{{}}` or `<>` turn it into its HTML entity code, which will later one (somewhere far away, I don't know where or when) turn back into =.
