### ISSUE TITLE
Add JSON Schema

### ISSUE THREAD

**Issue by jacopofar** [tatuylonen/wiktextract#193]
Hello!
When working on this data I found very useful to have a JSON Schema, from which it's easy to generate TypeScript or Pydantic definitions. I could not find any so I created one:

https://gist.github.com/jacopofar/277dd2290b99ca70d559f66514db5e73

I generated it using genson on a random sample of entries, then extended it by hand a bit for the PoS values and validated a whole dump with it to be sure there were no invalid entries.

Maybe you want to add it to the repo? It doesn't have documentation for the fields, but I can add some.

**Comment by kristian-clausal** [comment]
The format we use for Wiktionary data is not formalized, and can change at a whim. Creating a schema for a moving target can be counterproductive if users expect the data to conform to that schema and it doesn't. It's not just that we change it on purpose (although that can happen), it's that it can happen inadvertently.

On kaikki.org you can find https://kaikki.org/dictionary/errors/mapping/index.html which is a automatically updated crawl-map of all the data we output. It's not a machine-readable schema, but meant for human use.

Now, I noticed I've somehow messed up the breadcrump .pop()s somewhere, because those seem to be wrong, so please excuse me as I go and hit my head against some bugs...
