### ISSUE TITLE
Translations missing for "Portugal"

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#200]
Since a few weeks, all the translations of the English word [Portugal](https://kaikki.org/dictionary/English/meaning/P/Po/Portugal.html) seem to be missing. They are listed on a separate [translations subpage](https://en.wiktionary.org/wiki/Portugal/translations#English) and it seems that inclusion fails for some reason.

**Comment by kristian-clausal** [comment]
Is this actually a new issue, did the translations appear before, or have you only noticed this right now? This is an important distinction.

**Comment by kristian-clausal** [comment]
Fixed, but 50/50 whether this introduces new bugs. The issue was that {{see translation subpage}} did not have any arguments, so our code just returned with an error. I've changed this so that if there are no arguments, the parser will just do with defaulting to the same that wiktionary seems to do, language-level links. We'll just have to trust that people are diligent about adding POS parameters to these so that we don't have cross-contamination between different POS.

Another, stricter way to do this is default to having ctx.subsection, which might be more sensible. In the case of Portugal, the output is the same.

**Comment by ChristianSi** [comment]
Yeah, the translations have reappeared. Thanks!

**Comment by ChristianSi** [comment]
@kristian-clausal wrote:

> Fixed, but 50/50 whether this introduces new bugs.

I notice that the translations for [port](https://kaikki.org/dictionary/English/meaning/p/po/port.html) in the meaning "dock or harbour" are suddenly listed twice – both under the adjective and under the noun, though they only belong to the latter. This seems to have happened in the same dump where the "Portugal" issue discussed here was fixed. And the "port" page uses a translation subpage too. So it *could* be mere chance, but I rather suspect there might be a connection?

**Comment by kristian-clausal** [comment]
The translations were moved to a subpage last month, and the links on Wiktionary are broken, so *this one* is actually not our fault! 🥳 They used "Etymology 1: Noun" as a template argument, but that makes a link with an anchor called "#Etymology_1:_Noun", when it needs "#Noun_2" instead. You *can* change the template to have "Noun", "Adjective" and "Noun 2" for "Etymology 2: Noun", and then it'll work... But just a special case, I'll add a quick kludge to detect this very specific formatting.

**Comment by kristian-clausal** [comment]
This very specific formatting ("Etymology 1: Noun") is now detected. This problem is actually a wiktionary problem; I don't think {{see translation page}} can actually handle numbered Etymology sections, so people have to resort to using the argument as a title instead of as a link.

**Comment by ChristianSi** [comment]
Thanks for figuring this out! I see in the Wiktionary source code of the translation subpage they have manually set anchros such as `{{anchor|Etymology 1: Adjective}}` to make it work.

**Comment by kristian-clausal** [comment]
> Thanks for figuring this out! I see in the Wiktionary source code of the translation subpage they have manually set anchors such as `{{anchor|Etymology 1: Adjective}}` to make it work.

The thing is, it doesn't work, the anchor is broken! But the link works so it's fine.

**Comment by ChristianSi** [comment]
So, contrary to what your commit message says, these anchors aren't broken – they actually work.

**Comment by kristian-clausal** [comment]
Well, that's egg on my face. I just looked at the HTML source in the page index itself and assumed that that's what was used for everything, and then did some testing that I apparently failed at. Oh well. For our purposes, the link actually doesn't matter (yet?), happily or unhappily, we parse this using the hierarchy of the document and for that the path to it has to be constructed separately.

But now that it turns out that people use {{anchor}}, it might be usable with some effort.

**Comment by ChristianSi** [comment]
For "port", everything is now fine again. Thanks a lot.

 [Portugal](https://kaikki.org/dictionary/English/meaning/P/Po/Portugal.html), on the other hand, is now missing altogether – that link currently throws a 404. But I guess that might be a separate issue?

**Comment by kristian-clausal** [comment]
Messed up with None instead of "", should be fixed now.

**Comment by ChristianSi** [comment]
Yeah, it has re-appeared. Thanks!
