### ISSUE TITLE
Pronunciation data missing for Chinese entries

### ISSUE THREAD

**Issue by aaronhktan** [tatuylonen/wiktextract#210]
I was exploring the Chinese entries on kaikki.org, but it doesn't seem like any of the entries have pronunciation data.

Chinese pronunciation data appears to have been supported at some point in 2022. #65 contains a screenshot showing 阿姨 with IPA from three Sinitic topolects; presently, [kaikki.org](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%E9%98%BF/%E9%98%BF%E5%A7%A8/%E9%98%BF%E5%A7%A8.html) doesn't show any pronunciation data. #119 also mentions that parsing data from `zh-pron` is merged.

The JSON download from https://kaikki.org/dictionary/Chinese/nonsenses.html does not have pronunciation data, as far as I can tell.

Thanks for maintaining this project! I hope this issue can be easily fixed. :)

**Comment by kristian-clausal** [comment]
Should be fixed by 4773fc4.

Earlier, there was a problem with top-level templates in Pronunciation sections not being expanded early enough to be parsed (because the Pronunciation section starts off with the expectation that everything is contained in a wikinode LIST etc.), so I fixed that by checking if there was a LIST and then if not expanding all the top-level templates and hoping for the best.

However, zh-pron, which is this kind of top-level template, is handled separately, and the code identifying and parsing it needed the template to be whole so that it could do its [bespoke](https://en.wiktionary.org/wiki/bespoke)* parsing on it.

This was fixed by just adding a condition to check whether the template we were about to expand wasn't actually zh-pron.

`* Wiktextract Word of the Day.`
