### ISSUE TITLE
"welcome" incomplete

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#214]
Kaikki lists [welcome](https://kaikki.org/dictionary/English/meaning/w/we/welcome.html) as an adjective and interjection. However, [in Wiktionary](https://en.wiktionary.org/wiki/welcome#English) it's also a noun and a verb, and these meanings are altogether missing in Kaikki. (Since a few weeks or so, they used to be present earlier.)

Can you look into that please?

**Comment by kristian-clausal** [comment]
The page is now parsed completely, but the kaikki.org html doesn't show the gloss texts for some reason. I recently removed duplicated raw_glosses entries, time to check if we actually used those to generate the gloss text on the page...

**Comment by kristian-clausal** [comment]
Programming is such an amazing job; nowhere else can I create so much busywork for myself so easily!

Changed how raw_glosses are being deleted (all or nothing; if the whole list == glosses, delete it) because handling desynched lists would be a pain or even impossible. This way you can just replace glosses for raw_glosses.

Also fell down a rabbit hole when changing some of the tests for raw_glosses stuff, found a bug in parse_sense() relating to a kludge where we "promote" a lonely subgloss to the same level as its parent.

Kaikki's regen will start in a few hours, so it'll be ready by tomorrow.

**Comment by ChristianSi** [comment]
Thanks! The missing meanings and translations have re-appeared, so from my viewpoints (since I'm not using glosses) this is fixed.
