### ISSUE TITLE
Cantonese pronunciation data missing from some entries

### ISSUE THREAD

**Issue by aaronhktan** [tatuylonen/wiktextract#215]
In some entries, such as 車 (line 8 in the `All Chinese non-inflected, non-alternative word senses` JSON download from data extracted `2023-03-12`), the standard Guangzhou-Hong Kong Cantonese pronunciation data is missing. The link to the English Wiktionary page is here: https://en.wiktionary.org/wiki/%E8%BB%8A.

```
{
	"pos": "character",
	"head_templates": [{
		"name": "head",
		"args": {
			"1": "zh",
			"2": "Han characters"
		},
		"expansion": "車"
	}, {
		"name": "zh-hanzi",
		"args": {},
		"expansion": "車"
	}],
	"sounds": [{
		"tags": ["Mandarin", "Pinyin", "standard"],
		"zh-pron": "chē (che¹)"
	}, {
		"tags": ["Mandarin", "bopomofo", "standard"],
		"zh-pron": "ㄔㄜ"
	}, {
		"tags": ["Chengdu", "Mandarin"],
		"zh-pron": "ce¹"
	}, {
		"tags": ["Cantonese", "Taishan", "Wiktionary-specific"],
		"zh-pron": "cie¹"
	},

... [omitted for brevity] ...
```

I grepped the entire JSON and could not find any Cantonese pronunciation tag matching `Guangzhou-Hong Kong`, but I did find a few that had the tag `Guangzhou`.

Perhaps this is a result of the location tag being `Guangzhou-Hong Kong`, with a dash between the locations? It could also be that there are multiple pronunciations for this single character in Cantonese (but not Mandarin).

<img width="511" alt="Screen Shot 2023-03-14 at 12 19 28 AM" src="https://user-images.githubusercontent.com/14353716/224892307-ddca8c1d-8b69-49a4-b52f-5be18242a8b2.png">
<img width="511" alt="Screen Shot 2023-03-14 at 12 25 34 AM" src="https://user-images.githubusercontent.com/14353716/224893025-c9798531-bf1f-4629-81f3-dca1f97a6c56.png">

The character 西 (https://en.wiktionary.org/wiki/%E8%A5%BF, line 10 in the same JSON) has the same location tag but only a single pronunciation, and its Cantonese pronunciation is parsed correctly.

```
	"sounds": [{
		"tags": ["Mandarin", "Pinyin", "standard"],
		"zh-pron": "xī (xi¹)"
	}, {
		"tags": ["Mandarin", "bopomofo", "standard"],
		"zh-pron": "ㄒㄧ"
	}, {
		"tags": ["Chengdu", "Mandarin"],
		"zh-pron": "xi¹"
	}, {
		"tags": ["Cantonese", "Guangzhou", "Jyutping"],
		"zh-pron": "sai¹"
	}, {
		"tags": ["Cantonese", "Taishan", "Wiktionary-specific"],
		"zh-pron": "lhai¹"
	}, {
		"tags": ["Gan", "Wiktionary-specific"],
		"zh-pron": "xi¹"
	}, {

... [omitted for brevity] ...
```
<img width="505" alt="Screen Shot 2023-03-14 at 12 27 16 AM" src="https://user-images.githubusercontent.com/14353716/224893240-8929759e-5050-4578-b0bf-4d038c9ca377.png">

**Comment by kristian-clausal** [comment]
[Module:zh-pron](https://en.wiktionary.org/w/index.php?title=Module:zh-pron&action=history) has been changed recently, so we're just working on old data. The data on kaikki.org is taken from [en.wiktionary.org dump files](https://dumps.wikimedia.org/enwiktionary/) that are updated once or twice a month, so it takes a while for any changes made on Wiktionary itself to show in the kaikki.org data (or anyone else, for that matter).

Added an entry for "(Guangzhou–Hong Kong, Jyutping)" in wiktextract/wiktextract/data/zh-pron.json for now, but if one things changed then others will as well.

The data for "ce¹" is missing, though, so I guess I'll take a look at it more deeply.

**Comment by kristian-clausal** [comment]
I've not pushed a couple of fixes to the zh-pron bespoke parsing function.

1. Fixes some issues with detecting (Hokkien: Placename, Placename) style 'headers'
2. When the code can't find one of these candidate headers in the appropriate zh_pron_tags.json data or in valid_tags, it now generates proper debug messages instead of just lost prints in stdout
3. When the same line has several alternative pronunciations separated with commas or " / ", these are entered separately and not as one value as before.

With the proper debugging messages we'll soon have most of the data sources we need to later populate wiktextract/data/zh_pron_tags.json and tags.py (with the actual 'tags' like "Hong Kong" etc.), but I'll leave that for later and this thread open in the meanwhile. I might do these slowly as a drip, or if I get lazy I'll just wait until the next dump when the wiktionary-side changes to zh-pron have slowed down and do all the new tag data stuff in one go.

**Comment by kristian-clausal** [comment]
Made some changes in the parsing of zh-pron. These should improve the quality of tags by preventing some higher level tags from being used deeper in the bullet-list hierarchy when they shouldn't be. For example:

```
* (Hokkien: Something, Something Else, Other)
* * IPA (Something Else): pron¹
```

Here, `pron¹`, the pronunciation value, should not get the Something and Other tags, because it's specifically for Something Else. Currently, I've just fixed this issue specifically when IPA (X, Y, Z) is used, but it shouldn't be hard to generalize later if need be.

Also, instead of having to create a million entries in zh-pron.json with stuff like "(Hokkien: X, Y, Z)" and "(Hokkien: Z)" I've broken down this specific construction so that it's components parts are handled instead of the whole, which seems to work fine. Part of it is also part of how the issue with the mixed hierarchy tags is handled from above.

After this code has stopped being flux is the time to populate zh-pron.json and tags.py data with missing tags and data that we can find at that point in our debug data.

**Comment by aaronhktan** [comment]
As a follow-up, I'm able to see comma-separated values in for Cantonese Jyutping correctly. Hooray!

However, some comma-separated items with parentheses indicating alternative romanizations in Pinyin are not parsed correctly, such as the character `綠` ([link to Wiktionary](https://en.wiktionary.org/wiki/%E7%B6%A0)):
```
	"sounds": [{
		"tags": ["Mandarin", "Pinyin", "standard"],
		"zh-pron": "lǜ"
	}, {
		"tags": ["Mandarin", "Pinyin", "standard"],
		"zh-pron": "lù (lü⁴"
	}, {
		"tags": ["Mandarin", "Pinyin", "standard"],
		"zh-pron": "lu⁴)"
	}, {

... [omitted for brevity] ...
```
<img width="508" alt="Screen Shot 2023-03-16 at 3 02 06 AM" src="https://user-images.githubusercontent.com/14353716/225539802-7e8d5d0f-6025-4207-af74-c95bd93d6d83.png">

If you'd prefer I open a new issue for this instead of following up in this thread, let me know. Thank you so much for the quick bug triage + fix!

**Comment by kristian-clausal** [comment]
I think this doesn't need much to change, but it's a bit brutish: when we have `Something: pronunciations, other / pron.s (stuff, in parens)`, use parens as another delimiter alongside the comma and `' / '`. It might break something else, but that would have already been broken because the contents inside the parentheses would have been part of some other pronunciation value, which seems wrong as is.

**Comment by aaronhktan** [comment]
That approach works for most words, I think, but it also causes problems for words with commas in the zh-pron section, like `執輸行頭，慘過敗家` ([link to Wiktionary](https://en.wiktionary.org/wiki/%E5%9F%B7%E8%BC%B8%E8%A1%8C%E9%A0%AD%EF%BC%8C%E6%85%98%E9%81%8E%E6%95%97%E5%AE%B6)).
```
	"sounds": [{
		"tags": ["Cantonese", "Jyutping"],
		"zh-pron": "zap¹ syu¹ haang⁴ tau⁴"
	}, {
		"tags": ["Cantonese", "Jyutping"],
		"zh-pron": "caam² gwo³ baai⁶ gaa¹"
	}, {
... [omitted for brevity] ...
```
<img width="368" alt="Screen Shot 2023-03-16 at 9 16 19 PM" src="https://user-images.githubusercontent.com/14353716/225787443-0c633ced-4858-4920-a035-54a5d62b6766.png">

**Comment by kristian-clausal** [comment]
Then I'm out of ideas. If anyone can figure out some simple logic that will take care of edge-cases like that without breaking everything else, please let me know. Too much magic would need to happen for the system to figure out that that specific line corresponds to the whole title of the article, without messing up elsewhere with commas.

**Comment by kristian-clausal** [comment]
d36abc6

I implemented a very rough kludge. It does only this:
1. If there is a Chinese unicode comma "，" in the article title:
2. Split the pronunciation value on spaces, then add the number of commas
3. And compare with the number of characters in the original article title.
4. If so, do not split.

So it depends on the phrase transliterations doing a one-to-one space-separated syllable for each character, and kludges the number of commas used.

Happily, this doesn't break when the transliteration doesn't use a comma; in that case, it's not split anyhow, as we see in the last example in the example phrase.

**Comment by aaronhktan** [comment]
The recent change fixed the Jyutping parsing for commas!

But something broke for Pinyin with toneless final syllable variants. In the 2023-03-14 JSON, the parsing is correct for the word `食物`:

```
	}, {
		"tags": ["Mandarin", "standard"],
		"zh-pron": "shíwù → shíwu (toneless final syllable variant)"
	}, {
		"tags": ["Mandarin", "bopomofo", "standard"],
		"zh-pron": "ㄕˊ ㄨˋ → ㄕˊ ˙ㄨ (toneless final syllable variant)"
	}, {
```

But it broke in the 2023-03-17 JSON:

```
		"tags": ["Mandarin", "standard"],
		"zh-pron": "shíwù → shíwu "
	}, {
		"tags": ["Mandarin", "standard"],
		"zh-pron": "toneless final syllable variant"
	}, {
		"tags": ["Mandarin", "standard"],
		"zh-pron": ""
	}, {
		"tags": ["Mandarin", "bopomofo", "standard"],
		"zh-pron": "ㄕˊ ㄨˋ → ㄕˊ ˙ㄨ "
	}, {
		"tags": ["Mandarin", "bopomofo", "standard"],
		"zh-pron": "toneless final syllable variant"
	}, {
		"tags": ["Mandarin", "bopomofo", "standard"],
		"zh-pron": ""
	}, {
```

As far as I can tell, there's never any other case where `toneless final syllable variant` is in a `zh-pron` field, so maybe you could handle this situation by not using the parenthesis as a delimiter to split on when `toneless final syllable variant` is detected.

Thanks again for being responsive! I must be getting annoying by now 😄

**Comment by kristian-clausal** [comment]
I handled these final syllable variants by checking for the arrow, and then doing a special case pron-generation. Also added a new tag to be used here, "toneless-final-syllable-variant".

**Comment by aaronhktan** [comment]
Just tested it out, everything looks good to me! 🥳
