### ISSUE TITLE
Tagalog missing IPA data

### ISSUE THREAD

**Issue by lggruspe** [tatuylonen/wiktextract#216]
Only 1600 terms in the Tagalog dictionary JSON contain IPA entries.  The number should be ~14000 according to [this page](https://en.wiktionary.org/w/index.php?title=Category:Terms_with_IPA_pronunciation_by_language&from=T).

I noticed that many of the words with missing IPA entries use both `{{hyph}}` and `{{tl-IPA}}` templates.

Examples:

- [komedya](https://en.wiktionary.org/wiki/komedya#Pronunciation), [komedya](https://kaikki.org/dictionary/Tagalog/meaning/k/ko/komedya.html)
- [Gresya](https://en.wiktionary.org/wiki/Gresya#Pronunciation), [Gresya](https://kaikki.org/dictionary/Tagalog/meaning/G/Gr/Gresya.html)
- [sigang](https://en.wiktionary.org/wiki/sigang#Pronunciation),  [sigang](https://kaikki.org/dictionary/Tagalog/meaning/s/si/sigang.html)

**Comment by kristian-clausal** [comment]
Pushed a commit that should fix this: 51c057f

The issue was, as it often is, just a variable that was initialized outside a loop and never reset. For some reason when there's a `form` in {"ipa": "/something/", "form": "Hyphenation"} it gets rejected or removed at some point after the pronunciation section has been parsed and the data appended.

The fix was: move the initialization of `prefix` inside the loop iterating over the lines of the pronunciation section.

**Comment by kristian-clausal** [comment]
All three example words are now all correct (sounds > ipa data entries, and hyphenation > hyphenation entry), so I'll close this issue.

**Comment by lggruspe** [comment]
Thanks for the fix!
