### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'lang_code'

### ISSUE THREAD

**Issue by meturgut** [tatuylonen/wiktextract#224]
Even though it is installed in two packages (wiktextract and wikitextprocessor), I encountered the mentioned error when I used the following command.

Command: "python3 wiktwords --all --all-languages --out data.json enwiktionary-latest-pages-articles.xml.bz2"

Error: "Capturing words for: en, mul
Traceback (most recent call last):
  File "/Users/emin/Documents/wiktextract-test/wiktextract/wiktwords", line 283, in <module>
    ctx = Wtp(cache_file=args.cache, num_threads=args.num_threads,
TypeError: __init__() got an unexpected keyword argument 'lang_code'

**Comment by kristian-clausal** [comment]
That must mean the stuff on pip is out of synch with each other.

Please install from this repo and the wikitextprocessor repo.

**Comment by meturgut** [comment]
git clone https://github.com/tatuylonen/wiktextract.git
cd wiktextract && pip3 install -r requirements.txt && pip3 install -e .

I'm using this command that on wiktextract github page to download necessary packages. Is there anything else I need to do ? Thanks.

**Comment by kristian-clausal** [comment]
As I said, also install the wikitextprocessor repo instead of the pip install. These are both being worked on simultaneously, so if you install one, you need to install the other.

Remember to also git clone in another folder so that you don't have git folders inside each other. In this case

```
cd /Users/emin/Documens/wiktextract-test
pip3 uninstall wikitextprocessor
git clone https://github.com/tatuylonen/wikitextprocessor.git
cd wikitextprocessor && pip3 install -r requirements.txt && pip3 install -e
```

This will use the git folder as the source folder for the wiktextract and wikitextprocessor installations. If you update them with git pull, you're updating the installed files, so if you do update one you also need update the other.

**Comment by kristian-clausal** [comment]
I changed the README to include installation instructions for wikitextprocessor from repo.

**Comment by meturgut** [comment]
Thanks again, that's worked!
