### ISSUE TITLE
some more spurious romanizations

### ISSUE THREAD

**Issue by jmviz** [tatuylonen/wiktextract#233]
Following up on the comments on #230, I combed through the results of `grep -E '"form": "[A-Z][a-z]*-[A-Z][a-z]*.*", "tags": \["romanization"'` to find some more spurious romanizations. I made #232 to address all the cases that are clearly the same type of case as the "Proto-Romance" case from #230. There are two other clusters I found:

### 1
```
Čikobava
Klimov
Fähnrich-Sarǯvelaʒe
Fähnrich
Fähnrich-Sarǯvelaʒe 2000
Fähnrich 2007
```

These are found in Proto-Georgian-Zan/Proto-Kartvelian entries where the head line will look like [e.g.](https://en.wiktionary.org/wiki/Reconstruction:Proto-Kartvelian/%E1%B9%ADil%CA%BF-):

`{{head|ccs-pro|noun}} {{tlb|ccs-pro|Fähnrich-Sarǯvelaʒe}}` -> `*ṭilʿ- (Fähnrich-Sarǯvelaʒe)` 

They are using `{{tlb}}` to cite different authors' different reconstructions of word forms in these languages. I wasn't sure whether these should be handled in `uppercase_tags`, or `valid_tags`, or perhaps as a regex in some special case code.

### 2 

```
I-I
I-II
I-I-III
I-I-II
I-II-I
I-III
I-III-I
I-I-I
I-II-II
I-I-II-I
I-III-I-I
```

These seem to be per-syllable tone indications for Dungan words, [e.g.](https://en.wiktionary.org/wiki/%D1%85%D1%83%D1%8D%D0%B9%D0%B7%D1%9E): 

`{{head|dng|proper noun|I-II}}` -> хуэйзў [•](https://en.wiktionary.org/wiki/Wiktionary:Dungan_transliteration) (hueyzw) (I-II)

These would probably be best handled by a regex like `^I+(-I+)*$` somewhere. I wasn't sure what system if any is in place for handling tags etc. for tonal languages though.

**Comment by kristian-clausal** [comment]
upper_case tags contains stuff like what you've put there; languages, localities, dialects, etc. etc. tons of stuff that basically amount to "specifically *this*..." type of information, mostly. The less generic terminology, the more likely it goes in there; if it points to something specific in the real world, it goes there.

The Dungan tone tags will have to go somewhere else, I'll figure out where later after I get these tests working again. They definitely go into something in tags.py as individual entries. Most probably just as empty tags (that is, I-II -> nothing) because we don't have a flexible way of combining tags to create adhoc new ones, like what these tone markers require.

An alternative is just to create a whole new subsystem added to the head parser that parses for just these entries and adds them somewhere as new data...
