### ISSUE TITLE
Latin Pronunciations (IPA) Incorrectly Tagged

### ISSUE THREAD

**Issue by tjklemz** [tatuylonen/wiktextract#236]
The Latin pronunciations often seem to be incorrectly tagged as "Classical" instead of "Ecclesiastical", contrary to the Wiktionary data. You can see an example here:
- https://kaikki.org/dictionary/Latin/meaning/p/pr/praemitto.html
- Original: https://en.wiktionary.org/wiki/praemitto#Latin

```
"sounds": [
    {
      "ipa": "/prae̯ˈmit.toː/",
      "tags": [
        "Classical"
      ]
    },
    {
      "ipa": "[präe̯ˈmɪt̪ːoː]",
      "tags": [
        "Classical"
      ]
    },
    {
      "ipa": "/preˈmit.to/",
      "tags": [
        "Classical"
      ]
    },
    {
      "ipa": "[preˈmit̪ːo]",
      "tags": [
        "Classical"
      ]
    }
  ],
```

The last two should be tagged as "Ecclesiastical".

This appears to be inconsistent, as the following is correct: https://kaikki.org/dictionary/Latin/meaning/n/ni/nihil.html#nihil-la-pron-F4XPw7xq

**Comment by kristian-clausal** [comment]
That is weird. There's a bit on the backburner right now, so I'll take a closer look next week.

**Comment by kristian-clausal** [comment]
Well, the backburner was broken so I took a look at this.

Committed a fix. The issue was a bit annoying: la-IPA generates many lines of pronunciation data, but because it's put inside a list with an `*` the other kludges I have to expanding templates like this didn't trigger. The regex-heavy parsing portion of the code that handles singular lines couldn't handle this properly, so "Classical" which was caught by a specific regex was tagged while "Ecclesiastical" got put into a 'the rest of the text' bucket beside it.

Why didn't this happen in "nihil"? Because each instance of la-IPA used in nihil only created a single line because the authors skipped either the Classical or Ecclesiastical pronunciations because they wouldn't have made sense. `* {{la-IPA|nichil|cl=0}}` without the `cl=0` could generate a Classical "reconstruction" of 'nichil' that wouldn't make sense because the module underlying la-IPA doesn't work that way. The workarounds just coincidentally made the parsing work.

The HTML-generation server is down at the moment (upgrade gone bad), so you will see these changes on Kaikki.org next week at the earliest.

**Comment by tjklemz** [comment]
Thank you! I'll close this issue when I'm able to verify (unless you'd like it closed now).

I had no idea the complexity of Wiktionary data until looking into this project. Thanks again for your work; I really appreciate it.

**Comment by kristian-clausal** [comment]
I didn't look closely enough yesterday to notice the results were wrong (the values were repeated with both Classical and Ecclesiastical as tags), which was because of a bug (I was yielding/returning the wrong thing in one place). Should be fixed now.

**Comment by kristian-clausal** [comment]
`praemitto` seems to be correct now, so I'm closing this. If you find more wrongly parsed Latin pronunciations, just open a new issue, because it most probably is something a bit different than this specific case.

**Comment by tjklemz** [comment]
Everything looks good so far. I'll open a new issue if I see anything else. Thanks again.
