### ISSUE TITLE
support for ja-see and similar

### ISSUE THREAD

**Issue by garfieldnate** [tatuylonen/wiktextract#240]
I noticed today on kaikki that there is no page for 周り, which on Wiktionary is a redirect using `ja-see` to 回り. I'd like to implement this but I need a bit of guidance. I noticed there is already a note in TODO.

These are the templates that I know of that act similarly:

* ja-see: https://en.wiktionary.org/wiki/%E3%81%8D%E3%81%8D
* ja-see-kango: https://en.wiktionary.org/wiki/%E3%82%80%E3%81%B2
* ja-gv: https://en.wiktionary.org/wiki/%E3%81%A6%E3%82%93%E3%81%9F%E3%81%86%E3%82%80%E3%81%97

For each of these, I think the task is to just create a new sense for each linked word, with the word placed in the `alt_of` field. This is complicated, however, by needing to get the POS(s) from each linked entry. I'm uncertain of whether this requires a two-part process, where we save the redirected words in the first pass and find the POS and write out the data in the second pass, or if there's a more direct way to inspect linked entries through Wiktextract's API during single-pass processing.

**Comment by kristian-clausal** [comment]
Something similar is done with translation subpages. However, a problem here with PoS is that even if you follow the link, it doesn't tell you anything about the PoS. In the case of 周り it could be the Noun of Suffix, or the other Etymology section.

ja-see generates the box's contents semi-intelligently: it skips over the senses that have the wrong kanji variant, but include senses that don't have kanji at all, so 周り is associated with `(women's speech) side dish` without clear writing data.

In https://kaikki.org/dictionary/errors/mapping/index.html there is a top-level "alt_of" node... in 6 words, most or all which seem to be parsing errors of heads. Yeah, gotta take a look at that. But it's not inconceivable that we could just create an entry that's a bare-bones redirect straight to another word entry or entries, like a "redirect" field.

**Comment by garfieldnate** [comment]
I ended up simply writing a separate script to extract the POS, surface, and alt_of data. Two simplifying observations helped:

* The templates have more available features than are actually used. Besides the linked page title parameter, generally only the `key` parameter is used (that's the form to look for on the linked page). There were a couple instances of others, but I simply edited the raw Wiki text in those cases to make sure everything would work right.
* Technically the `key` parameter is supposed to be searched for in `{{ja-pos...}}` etc. present on the linked page, but since I only needed the POS it worked fine to just look for the POS section containing the form anywhere in its text.

I ended up with 39K redirects, which will be very helpful for normalizing Japanese text.

Here's the data I extracted, along with the scripts I used:
[ja-redirects.zip](https://github.com/tatuylonen/wiktextract/files/11382073/ja-redirects.zip)

**Comment by kristian-clausal** [comment]
AFAICT, Lua templates are by design quite separated from each other by the Scribunto designers. That's why the strip-marker hack in Japanese templates that break our parser currently over in that other issue are non-kosher: there shouldn't be cross-contamination or templates that get data in funky ways, it should all be clean/functional: you give arguments to a template, and that template or module might call on other templates or modules beyond that, but a template shouldn't be able to affect another template on the same level it is; there are no templates (AFAICT) that let you create something like a variable, for example. {{multitrans}} and {{trans-top}} seem funky at first glance, but I think trans-top kind of just creates some HTML bookends and multitrans just eats up all the {{tt}} templates as arguments instead of letting them be run individually, which speeds things up, then spits out a list of translations.

Besides that, we can't have pages affecting other pages when the pages "affected" isn't the one being parsed. We can *pull* data from "See translation" pages, but we can't *push* data from pages with Ja-see templates, because the targeted page might or might not have been parsed already etc.

You'd need to create a whole new system that allows you to go back to already parsed data to change it, or go forward in time and save data for a page that hasn't yet been parsed.

Writing that out, I've mostly described "post-processing".

**Comment by garfieldnate** [comment]
So how does Wiktionary do this, then? Are the pages re-rendered multiple times until an equilibrium is reached?

**Comment by kristian-clausal** [comment]
{{ja-see}} apparently loads the Wiktionary source of the page ja-see points at, and does a lot of pattern matching to find the data. It basically goes "find a line that goes `{{ja\-pos(\||}` or [pattern] or [pattern] or [pattern] or... and then do funky string substitution stuff with it". It pulls data straight from the target Wiktionary article's text, stealing arguments from unexpanded templates and so the target article does not need to be parsed (in Wiktextract you can parse the target page, that's what we go with "See translation" pages).

`きき` can pull data from `危機`, but it can't affect `危機`, you can't add data to it based on what's in `きき`.
