### ISSUE TITLE
Some translations get treated as notes

### ISSUE THREAD

**Issue by lggruspe** [tatuylonen/wiktextract#243]
Example: [ISBN](https://kaikki.org/dictionary/English/meaning/I/IS/ISBN.html)

I'm not sure if this is the intended behavior, but some of the translations are put in the "note" field instead of "word".

**Comment by kristian-clausal** [comment]
Figured it out: in translations.py we have

```python
            else:
                # Interpret it as an actual translation
                parse_translation_desc(ctx, lang, part, tr)
                w = tr.get("word")
                if not w:
                    continue  # Not set or empty
                if w.startswith(("*", ":")):
                    w = w[1:].strip()
                if w in ("[Term?]", ":", "/", "?"):
                    continue  # These are not valid linkage targets
                if len(w) > 3 * len(word) + 20:
                    print(w)
                    # Likely descriptive text or example
                    del tr["word"]
                    tr["note"] = w
```

Where the last if-branch checks to see if the translation is three times the length of the word we're looking at + 20 characters; that is, whether the translation is a lot longer than expected. Of course, this doesn't take into account acronyms like 'ISBN', so I'll figure out a way to see if we can skip this if everything is capitalized.

Most of the other translations do not look English enough to get this far down the conditions.

**Comment by kristian-clausal** [comment]
Fixed by checking word.isupper(), which should return true if there are latin characters that are all in uppercase (so 'I.S.B.N' also works).

**Comment by kristian-clausal** [comment]
Seems to be fixed in the case of `ISBN`. Things can break down (I can think of a few possible scenarios), like a term in a foreign script that has a single uppercase Latin letter that gets detected as an acronym because there are no lowercase Latin letters otherwise (Japanese, I'm looking at you), but hopefully those are nonexistent or extremely rare. In those case, we can make a bit more elaborate (and a bit more costly) detection for non-Latin characters...
