### ISSUE TITLE
no definition of the word "nature" in the french dictionary

### ISSUE THREAD

**Issue by SuperUserNameMan** [tatuylonen/wiktextract#244]
Hello,

This might be indicative of a bug in wiktextract ?

The word "nature" does not have definition into the french dictionary here : https://kaikki.org/dictionary/French/kaikki.org-dictionary-French.json

The json contains 4 reference to `"word": "nature"`, but none is a definition.

Do you want me to inform you about other missing definitions if i find more ?

**Comment by kristian-clausal** [comment]
Thanks for pointing it, it's taken me a while to work up through other issues. This looks like it's not specific to French; every other entry in 'nature' is missing. I'll take a look at it now, and we'll see what I'll uncover.

**Comment by kristian-clausal** [comment]
It's our friend, {{multitrans}}. Template:multitrans is a module used to better optimize the resource use of large translation sections: it basically takes as input all the various translation lines (as {{tt}} or {{tt+}}) and handles them all at once instead of each one separately, due to the way that the {{trans-top}} and {{trans-bottom}} templates/tags work... I think.

I had to kludge something that was causing problems with it yesterday, but that's a different issue. In this case, the HTML parsing is broken, the closing tags for tables and divs are left as text and not picked up; then those pieces of texts are discarded with an error, and the open elements are complained about.

This is going to be a pain. :+1:

**Comment by kristian-clausal** [comment]
I've taken out the shepherd's stadd and herded trans-top, trans-bottom, checktrans-top and checktrans-bottom from the safety of unexpanded template space into the list of pre-expanded templates, together with multitrans.

Hopefully the HTML-parsing will not be wonky if all these templates are expanded before they are parsed initially.

This means that we can't actually utilize the attribute data (like 'sense' in trans-top) directly, but we are already doing things without them (except for the commit I did earlier this week that did use attribute data, but it should work now...) so there shouldn't be any difference. Hopefully.

**Comment by kristian-clausal** [comment]
At least `nature` seems to be looking complete, so I'm closing this issue. If you find something else missing, it's probably (hopefully) a different issue and worthy of a new thread.
