### ISSUE TITLE
^ and ( ) in zh IPA

### ISSUE THREAD

**Issue by lggruspe** [tatuylonen/wiktextract#252]
Some Chinese words have ^ in their IPA. I think this is an error, because the Wiktionary pages don't have this symbol.

Examples:

- /a⁵⁵ ^((kʰ-))uaŋ⁵³/ in https://kaikki.org/dictionary/All%20languages%20combined/meaning/%E4%B8%AB/%E4%B8%AB%E9%AC%9F/%E4%B8%AB%E9%AC%9F.html
-  /kɛiŋ²¹³⁻⁵³ ^((Ø-))ŋuaŋ³³/ in https://kaikki.org/dictionary/All%20languages%20combined/meaning/%E3%AA%A0/%E3%AA%A0%E7%A2%97/%E3%AA%A0%E7%A2%97.html

Additionally, there seems to be another bug that causes parentheses in IPA transcriptions to split the transcription into multiple parts. (See examples above.)

**Comment by kristian-clausal** [comment]
The ^() shows superscript text, I believe. I'll take a look at the splitting, it should be all happening in one place so shouldn't be difficult.

**Comment by kristian-clausal** [comment]
Fixed by [1c6974b](https://github.com/tatuylonen/wiktextract/commit/1c6974b3120a8bd9a997f5e85edb10fdfd34473b)

I was splitting on parentheses, fix is not to split on parentheses if those are in a string with bookending /'s. There are ways for this to break down (like `/ipə/ (text) /ipə/`) but they seem unlikely.
