### ISSUE TITLE
Some Reconstruction words have incorrectly expanded head templates

### ISSUE THREAD

**Issue by jmviz** [tatuylonen/wiktextract#268]
The only immediately apparent commonality in the examples I have come across is that the language names have spaces. Examples:

`Old Dutch` `thicki` [wiktionary](https://en.wiktionary.org/wiki/Reconstruction:Old_Dutch/thicki), [kaikki](https://kaikki.org/dictionary/Old%20Dutch/meaning/t/th/thicki.html)

```json
"head_templates": [
    {
      "args": {
        "1": "odt",
        "2": "adjective"
      },
      "expansion": "*Old Dutch/thicki",
      "name": "head"
    }
  ]
```

`Ashokan Prakrit` `𑀞𑀕𑁆𑀕𑁆-` (the special characters in this word may not render here) [wiktionary](https://en.wiktionary.org/wiki/Reconstruction:Ashokan_Prakrit/%F0%91%80%9E%F0%91%80%95%F0%91%81%86%F0%91%80%95%F0%91%81%86-), [kaikki](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%F0%91%80%9E/%F0%91%80%9E%F0%91%80%95/%F0%91%80%9E%F0%91%80%95%F0%91%81%86%F0%91%80%95%F0%91%81%86-.html)

```json
"head_templates": [
    {
      "args": {
        "1": "inc-ash",
        "2": "reconstructed noun",
        "g": "m"
      },
      "expansion": "*Ashokan Prakrit/𑀞𑀕𑁆𑀕𑁆- (*Ashokan Prakrit/ṭhagg-) m",
      "name": "head"
    }
  ]
```

`Old Norse` `bljúgr` [wiktionary](https://en.wiktionary.org/wiki/Reconstruction:Old_Norse/blj%C3%BAgr), [kaikki](https://kaikki.org/dictionary/Old%20Norse/meaning/b/bl/blj%C3%BAgr.html)

```json
"head_templates": [
    {
      "args": {
        "1": "non",
        "2": "adjectives",
        "head": ""
      },
      "expansion": "*Old Norse/bljúgr",
      "name": "head"
    },
    {
      "args": {},
      "expansion": "*Old Norse/bljúgr",
      "name": "non-adj"
    }
  ]
```

This doesn't always happen though. For example, I randomly checked this one which expands correctly:

`Old English` `tasan` [wiktionary](https://en.wiktionary.org/wiki/Reconstruction:Old_English/tasan), [kaikki](https://kaikki.org/dictionary/Old%20English/meaning/t/ta/tasan.html)

```json
"head_templates": [
    {
      "args": {
        "head": "*tāsan"
      },
      "expansion": "*tāsan",
      "name": "ang-verb"
    }
  ]
```

**Comment by kristian-clausal** [comment]
I'll take a look, might have to wait until next week.

**Comment by kristian-clausal** [comment]
It was an issue with template expansion. {{inflection of}} had {{no deprecated lang param usage}} inside of it at the same time that it generated the two `##` lines, so the `##` items got put inside of no-deprecated:

```
# {{no deprecated lang param usage|inflection of ...
## .....
## ..... }}
```

and no-deprecated interfered with the parsing of the list because it had to be expanded *before* we started to parse the list.

Fix: pre-expand inflection_of and no_deprecated, that's what the pre-expand step is for: getting templates out of the way if they create difficult-to-parse structures, like here.

As long as kaikki updates (WHICH SHOULD HAPPEN please, PLEASE) this should be visible there in a couple of days.
