### ISSUE TITLE
some glosses generated by template `inflection of` are rendered with wikitext # markup

### ISSUE THREAD

**Issue by jmviz** [tatuylonen/wiktextract#269]
Examples:

`Latin` `compositura` [wiktionary](https://en.wiktionary.org/wiki/compositura#Latin), [kaikki](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/co/compositura.html)

`# {{inflection of|la|compositūrus||nom//voc|f|s|;|nom//acc//voc|n|p}}`

```json
"glosses": [
        "inflection of compositūrus:\n## nominative/vocative feminine singular\n## nominative/accusative/vocative neuter plural",
        "nominative/accusative/vocative neuter plural"
      ],
```

`Ancient Greek` `ξενία` [wiktionary](https://en.wiktionary.org/wiki/%CE%BE%CE%B5%CE%BD%CE%AF%CE%B1#Ancient_Greek), [kaikki](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%CE%BE/%CE%BE%CE%B5/%CE%BE%CE%B5%CE%BD%CE%AF%CE%B1.html)

`# {{inflection of|grc|ξένῐος||f|nom//voc|s|;|f|nom//acc//voc|d}}`

```json
"glosses": [
        "inflection of ξένῐος (xénios):\n## feminine nominative/vocative singular\n## feminine nominative/accusative/vocative dual",
        "feminine nominative/vocative singular"
      ],
```

**Comment by kristian-clausal** [comment]
Yep, there's something funky going on. There's holidays coming up, so things might happen only next week, but it's on the list.

**Comment by kristian-clausal** [comment]
It was an issue with template expansion. {{inflection of}} had {{no deprecated lang param usage}} inside of it at the same time that it generated the two `##` lines, so the `##` items got put inside of no-deprecated:

```
# {{no deprecated lang param usage|inflection of ...
## .....
## ..... }}
```

and no-deprecated interfered with the parsing of the list because it had to be expanded *before* we started to parse the list.

Fix: pre-expand inflection_of and no_deprecated, that's what the pre-expand step is for: getting templates out of the way if they create difficult-to-parse structures, like here.

As long as kaikki updates (WHICH SHOULD HAPPEN please, PLEASE) this should be visible there in a couple of days.

I'm off for the holidays, see you next week.

**Comment by kristian-clausal** [comment]
This seems to be resolved, and kaikki has updated.

The website-generation process (that is, wiktextract + html generation) is succeeding (for the first time in a few weeks!) but unfortunately the upload process seems to be hazardous... At least the connection held a couple of times when I was away on my break, so there's a new updated kaikki with the most recent changes.
