### ISSUE TITLE
URLs in synonyms

### ISSUE THREAD

**Issue by lggruspe** [tatuylonen/wiktextract#274]
Some words have URLs in their list of synonyms.

- [Hehe](https://kaikki.org/dictionary/All%20languages%20combined/meaning/H/He/Hehe.html)
- [debaptism](https://kaikki.org/dictionary/All%20languages%20combined/meaning/d/de/debaptism.html)

**Comment by kristian-clausal** [comment]
I got stuck on a thing as I was navigating towards your issue (I can't believe I forgot the implicit return of lambdas AGAIN), so I'll be taking a look at it tomorrow, or today if things go well.

**Comment by kristian-clausal** [comment]
Fixed by 6e1968e2eed3db732419c63d2710cbc30350ddb5

The issue was with "naked" urls like the `[1]` after `Wahehe` in Hehe. The extractor assumed that we would want to use *some* text from the URL node, so it always used `node.args[-1]` for that; the args for URL WikiNodes are basically just "list of urls, list of str text" where the latter is the visible portion of a link.

When the url was passed upward, the text of the url was mangled at some point, by splitting at `/` for some other purpose (tons of things need to be split on slashes), though I didn't look too deep into it there.

The fix is to extract the url data from URL WikiNodes into a separate, new field called "urls". The visible link portion is handled much the same as before, as part of the text.
