### ISSUE TITLE
Some translations appear to be missing

### ISSUE THREAD

**Issue by lggruspe** [tatuylonen/wiktextract#275]
For example, [father](https://kaikki.org/dictionary/All%20languages%20combined/meaning/f/fa/father.html) and [snake](https://kaikki.org/dictionary/All%20languages%20combined/meaning/s/sn/snake.html) don't have any translations.

**Comment by kristian-clausal** [comment]
Fixed in d0ec66287f216c69ea3ae74e82a3a0046cc42e8c

Newlines inside template arguments caused the parser to evaluate `|` pipe characters at the start of the line as table row markers instead of template argument separators, and I don't know why a test we already had would pass when this bug existed. xxyzz came up with a simple solution to just change the context flag for "are we at the beginning of a line?" when looping through the template arguments so that this doesn't happen.

**Comment by xxyzz** [comment]
No, this bug doesn't involve any table related code. That `ctx.beginning_of_line = False` line is for avoid popping the template node from parser stack later in the `text_fn()`(please see the [stack trace](https://github.com/tatuylonen/wikitextprocessor/pull/70#issuecomment-1617478656)). And the test `test_template3` could pass is because that test template is not inside a list.

**Comment by kristian-clausal** [comment]
Yeah, text_fn() popped the stacks, which caused the test in vbar_fn that checks whether it is inside a template to fail, which is what made me think it was table-related code; the relevant change was in process_text -> ... -> text_fn -> close_begline_lists().
