### ISSUE TITLE
Missing definition for some English words

### ISSUE THREAD

**Issue by nickeb96** [tatuylonen/wiktextract#285]
There appears to be 331 words without a definition.  A good example to look at is *ox*, which has a definition on [wiktionary](https://en.wiktionary.org/wiki/ox), but not in the extracted json files.

**Comment by xxyzz** [comment]
I checked some JSON data with the "no-gloss" tag and I think I should record some cases I have seen so far:

- the word doesn't have gloss on Wiktionary: [pseudoholomorphic](https://en.wiktionary.org/wiki/pseudoholomorphic), [noctivore](https://en.wiktionary.org/wiki/noctivore)
- gloss is not in a list: [Jeuk](https://en.wiktionary.org/wiki/Jeuk)
- the pos subtitle should be etymology: [legharness](https://en.wiktionary.org/wiki/legharness)
- the whole gloss is inside parentheses: [jaw](https://en.wiktionary.org/wiki/jaw#Adjective)
- broken template: [Poes](https://en.wiktionary.org/wiki/Poes)
- uses "place" template: [KwaZulu-Natal](https://en.wiktionary.org/wiki/KwaZulu-Natal)
- has `<math>` tag: [Jackson integral](https://en.wiktionary.org/wiki/Jackson_integral)
- uses "ux" template: [onesie](https://en.wiktionary.org/wiki/onesie), this one should be fixed by remove the example ignore code in `extractor.en.page.parse_language.parse_sense_node.sense_template_fn()`.
- has <ref name="x"/>: [apanthropinisation](https://en.wiktionary.org/wiki/apanthropinisation), fixed in #286
- only have one gloss list item: [ARF](https://en.wiktionary.org/wiki/ARF), fixed in #286
- headword line has category template: [ox](https://en.wiktionary.org/wiki/ox), fixed in #286

**Comment by xxyzz** [comment]
I think I have fixed most fixable cases. Please post the cases I have missed if you find any.

**Comment by nickeb96** [comment]
Just to clarify, does the json list at <https://kaikki.org/dictionary/English/index.html> have these changes in it? Or do I need to build it locally?

**Comment by xxyzz** [comment]
kaikki.org probably won't update very often recently because Kristian is on vacation. You could run the `wiktwords` command on your local machine in the meantime.
