### ISSUE TITLE
Missing headword templates, Russian

### ISSUE THREAD

**Issue by jsannemo** [tatuylonen/wiktextract#314]
Sometime since June, the following word: https://en.wiktionary.org/w/index.php?title=%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80&action=edit&section=10

stopped having its `head_templates` parsed. None appear in the latest dump: https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D0%B2/%D0%B2%D0%B5/%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80.html

**Comment by kristian-clausal** [comment]
The head templates are parsed and the data is there:

```
    {
      "form": "ве́кторы",
      "source": "declension",
      "tags": [
        "nominative",
        "plural"
      ]
    },
```

There is no `head_templates` field, which is mildly weird, but kind of low-priority at the moment. I'll take a look at it later this week.

**Comment by jsannemo** [comment]
Thanks!

After some comparisons, it seems like specifically headword templates that have a trailing <br /> tag on the same line aren't added.

**Comment by kristian-clausal** [comment]
The culprit is the `<br />`. Having two head templates back to back doesn't help either.

Because there are a million ways that people put head templates here and there, sideways or upside down, the code trying to figure out what is happening is messy and I thought I had already solved this ages ago.

This might just be unsolvable and I am feeling frustrated with the problem. Spaghetti in, spaghetti out.

**Comment by kristian-clausal** [comment]
Specifically, the second `<br />` is what causes the most issues; it's basically a double-newline, which means "big section break", but the author hasn't noticed it because they just copy-pasted it from the line above (where it is necessary to break up the lines? There is a paragraph break with an extra newline, but not with `<br />`). What a mess.

**Comment by kristian-clausal** [comment]
You've led me on another rabbit chase, jsannemo. This *should* be fixed for now, but issues will arise elsewhere. We'll deal with that when the time comes!

I just wrote a long and rambling commit message, so I'll just summarize:

Newlines were breaking up a parallel list we were creating of heads and their glosses lists in ways that "desynched" the list; that's now fixed by a bit of kludgy code that removes empty pairs of heads/glosses and pairs up orphans.

I also commented out a piece of code that skipped the parsing of heads that didn't have a gloss list associated, which broke other things related to parsing stuff where people just write "1. gloss" style lists by hand, but I think that's fixed now.
