### ISSUE TITLE
Potential bug while parsing example with a URL in the reference

### ISSUE THREAD

**Issue by zakeryooo** [tatuylonen/wiktextract#321]
Hi, for sense examples if there's a URL (google books in this case) to the reference it seems to not get detected and instead display the URL in the "text" property:

https://en.wiktionary.org/wiki/gummy
https://kaikki.org/dictionary/English/meaning/g/gu/gummy.json

```
            {
               "text":"2007, Bill Classon, Fishing Guide to Victoria′s Coastline, Australian Fishing Network, %22gummies%22+shark+-intitle:%22%22+-inauthor:%22%22&hl=en&sa=X&ei=6mJwT5emO4PcmAWlpImSBg&redir_esc=y#v=onepage&q=%22gummy%22 %22gummies%22%20shark%20-intitle%3A%22%22%20-inauthor%3A%22%22&f=false page 60,\nWestern Port is a great location to find gummies. […] Gummy sharks are one of the favoured species in Western Port and for good reason: they put up a strong fight and feed of fresh flake is pretty hard to beat."
            },
```

Is the intended behaviour or a bug? Thanks!

**Comment by kristian-clausal** [comment]
Found a bug in the code that handles this for glosses; "Category:" links were being ignored because the `regex.group` index that was being compared to stuff taken from NAMESPACE was off by one and thus you'd compare "Category:" (wrong) with "Category".

This bit of code could probably be refactored into its own, and might be compatible with the stuff in examples if that also does stuff with detecting links through regexes in the same way.

**Comment by kristian-clausal** [comment]
Well there's your problem: the hyperlink that is broken looks like `[https://www.this.com/urlparamtergibberish|more|more=false Page 60]` which should technically be a broken link seeing as how:

> [Titles containing certain characters will display and link incorrectly unless those characters are encoded with HTML character references.](https://en.wikipedia.org/wiki/Help:URL)

But apparently Wikimedia code is smart enough to detect these unescape URLs anyhow, passing them to us. Programming is a never-ending feverdream from which none of us may ever awaken.

**Comment by kristian-clausal** [comment]
I think this actually might be that URLs in the `[http://url.com text]` don't just have any `|` delimiters, which is what our code assumes. Changing that is turning into a minor headache.

**Comment by kristian-clausal** [comment]
So, there was a minor bug in Wikitextprocessor. There are a bunch of wikitext elements that use `|` vertical bars as separators; links, templates, etc. so Tatu must have assumed that this held true for URLs as well, which wasn't actually the case. These were all lumped into HAVE_ARGS_KIND and used in a couple of places for a couple of things, one of which was when parsing the `|`-token: here's where the urls containing vbars were split into separate arguments, which messed things up for other things. A simple fix in this case is to just put an extras `node.kind is not NodeKind.URL`  in the condition.

This led me on a big goose chase, because as I changed things elsewhere things would break in weird ways, because searching around for `NodeKind.URL` didn't show me the important bits with HAVE_ARGS_KIND that would have explained a lot of the weirdness I was causing. But I eventually figured it out.

The result is that URLs are now either expressed as naked urls (if they didn't have any other text inside the brackets), which would be a `[1]^` style link on wikipedia, or just the link's visible text for now. Getting the data out into data fields might be in the works, but that's for later.
