### ISSUE TITLE
[Term?] in etymology

### ISSUE THREAD

**Issue by william-davies** [tatuylonen/wiktextract#343]
I downloaded `JSON data for all word senses in the Spanish dictionary (611.7MB)` from [here](https://kaikki.org/dictionary/Spanish/kaikki.org-dictionary-Spanish.json).

The `etymology_text` for the word `deber` is as follows:
`"etymology_text": "Inherited from Old Spanish [Term?], from Latin dēbēre (“owe”). Cognates include English due and debt.",`. Here is the full JSON object for `deber`: [deber-json.txt](https://github.com/tatuylonen/wiktextract/files/12678422/deber-json.txt)

Looking at the Wiktionary [page](https://en.wiktionary.org/wiki/deber#Spanish) it should be `Inherited from Old Spanish dever, from Latin dēbēre (“owe”). Cognates include English due and debt.`. Looks like the `dever` is becoming `[Term?]` in the expansion.

I admit that this is a minor "bug" but would appreciate a fix if you have time (or an explanation if I've just misunderstood something/am being silly)!

Thank you for such a great resource!

**Comment by xxyzz** [comment]
The file you downloaded was created from the 20230901 dump file, and the "deber" page was updated at Sep 3th which fixed the `[Term?]` text. This will be fixed maybe today when the new 20230920 dump file is used.

**Comment by kristian-clausal** [comment]
It'll take a little longer. The server is up now, but the most recent outage was just that the machine needed booting after security updates (and no one was there to do it), but before that we had issues where the HD was filled up with new data generated by some bug-fixes. I made a commit to the kaikki repo's regeneration script, but forgot to actually push it... So when the server was running again, it filled up again with an old2 backup's-backup copy of the website. I've now deleted the backup, the commit has been pushed to the kaikki repo, so there should be a run that should be finished with 24h.

I encourage people to still post these kinds of issue threads, just in case. As a plus, when it turns out it's not our fault (like in this case, with the old wiktionary dump) we get to close the thread and feel good about not having to do anything about it, the best kind of issue.
