### ISSUE TITLE
Preserving word link information from glosses

### ISSUE THREAD

**Issue by Palmik** [tatuylonen/wiktextract#38]
Thanks a lot for this awesome tool! I wonder if you thought about ways to preserve the way words are interlinked through glosses. Perhaps just an option to not remove `[[...]]` links from the glosses.

**Comment by tatuylonen** [comment]
I agree this could be useful in some applications...  on the other hand the links in Wiktionary are rather arbitrary and I wonder how useful they really would be.  The actual implementation of such a feature shouldn't be very hard though.

Do you have a clear use for such an option in mind?

There are some special kinds of links that I think clearly should be collected (and actually were collected in an earlier versions), including taxonomic links, colors, and number values (some this data is displayed as tables in word entries).  Collecting these in the new version is still on my todo list.  However this is a bit different from what you are asking.

**Comment by thomasgauthier** [comment]
I think that this would be a useful feature. For example preserving wikilinks would enable linking to english glosses for foreign words that do not contain a full definition (e.g. https://en.wiktionary.org/wiki/katxor, https://en.wiktionary.org/wiki/k%C3%ABr).

**Comment by ilyafreer** [comment]
It is very necessary to add the option to save links [[...]]
The definitions doesn't explain the meaning fully. The user has to click to the linked term to get the meaning. That's why having a link is so benefitial and required for better user experience.
For example here links to make can be very helpful
![For example](https://i.ibb.co/jzJrF2b/image-2023-02-17-13-39-58-417.png)

**Comment by kommepc** [comment]
We also have a similar requirement. Links to other terms are an essential part of definitions.

**Comment by kristian-clausal** [comment]
3cee0cf adds a new field into a sense in `senses`: a list of lists/tuples, where the first item of a tuple is the visible text of the link and the second item is the link path itself.

To keep it simple, we skip over anything that starts with a `Namespace:something` style prefix, except for Category: because we already captured Category data in the previous versions and the new code kind of fit perfectly in the same area. So `Appendix` is ignored, as it should be here.

The link path is just the literal link path without the prefix, `make#English` style.

Anything much else would be pretty hardcore thaumaturgy. Can't create data out of thin air, and that's not the purpose of wiktextract, so if a link on Wiktionary is kind of vague, it's going to be kind of vague here too.

As soon as we get the kaikki regen running again it should be in the json data on kaikki.org, but formatting it in html hasn't been done yet (and might be just skipped). Not tomorrow, because I've already set it running this morning, but maybe, maybe on Friday and hopefully next week.

**Comment by kristian-clausal** [comment]
Almost forgot about checking whether this worked out, but looking at [makes](https://kaikki.org/dictionary/All%20languages%20combined/meaning/m/ma/makes.html), the json data now has the `links` field in the senses.

```json
 "senses": [
    {
      "categories": [
        "English terms with usage examples"
      ],
      "examples": [
        {
          "text": "Green traffic lights look white to me, which makes them hard to distinguish from streetlights from far away."
        }
      ],
      "form_of": [
        {
          "word": "make"
        }
      ],
      "glosses": [
        "Third-person singular simple present indicative form of make"
      ],
      "links": [
        [
          "make",
          "make#English"
        ]
      ],
      "raw_glosses": [
        "Third-person singular simple present indicative form of make"
      ],
      "tags": [
        "form-of",
        "indicative",
        "present",
        "singular",
        "third-person"
      ]
    }
  ]
```

**Comment by kristian-clausal** [comment]
Btw, I took a look at saving link data inside the raw_glosses strings somehow, but there are too many issues and it would use an annoying amount of memory.

At one point we have a node from the abstract parsing tree that we have received from Wiktionary; this is just a tree of WikiNodes and strings, so the actual LINK `[[]]` stuff is gone by the time it gets to the part where we generate glosses and raw_glosses: clean_node() just returns text without formatting and html entities by interpreting the parse tree of the node.

*Technically*, you could get a string out of clean_node() that contains `[links]` or a magic string `__bl__links__br__` or something similar by modifying clean_node() and giving it a "preserve links" parameter, but having those extra characters in the string could easily break the other string manipulations we do after we receive it, *or* if we call clean_node() twice to get a version of the string with and without the markers we would have problems keeping the two different strings "in synch": both of the strings would have to be manipulated in the same exact manner, but the output is not guaranteed to be "equivalent". The output clean_node() is not a single gloss; in this example, it could be several glosses, which need to be split up in a sensible manner.

In addition, doing it with two strings in parallel like that would be a lot of processing time, because parsing glosses is being done a lot. It's too much effort for something that most probably wouldn't be very useful as machine-readable data, and a human should be able to figure out how to insert the extract links pretty much automatically.
