### ISSUE TITLE
Wrong URLs for "Unsupported titles"

### ISSUE THREAD

**Issue by digitalheir** [tatuylonen/wiktextract#380]
A lot of `cv:{x}` entries, which ~do not seem like words to me but are listed as forms of the acronym of 'curriculum vitae'. Something went wrong with template expansion?~ have wrong URL to Wiktionary. Entry does exist on Wiktionary, but with a different URL.

https://en.wiktionary.org/wiki/Unsupported_titles/cv:s

The colon is common for abbreviations.  

> the colon is used for some abbreviations, such as 3:e for tredje ("third") and S:t for Sankt ("Saint"), and for all types of endings that can be added to numbers, letters and abbreviations, such as a:et ("the a") and CD:n ("the CD"), or the genitive form USA:s ("USA's").

[source](https://en.wikipedia.org/wiki/Swedish_language#cite_ref-69)

https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv:s.html
https://kaikki.org/dictionary/All%20languages%20combined/meaning/C/CV/CV:s.html
https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv:t.html
https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv:n.html

The 'Wiktionary' link redirects to some template page in a (Turkic?) language unknown to me, written in Cyrillic/Latin. But should be in some special "Unsupported titles" category: https://en.wiktionary.org/wiki/Unsupported_titles/cv:s

[**cv**:](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv.html)

>Inflected forms
>
>    [cv-er (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-er.html#cv-er-nb-noun-rKD3Sqs2) [Norwegian Bokmål] indefinite plural of cv
    [cv-a (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-a.html#cv-a-nb-noun-dMV~64xF) [Norwegian Bokmål] definite plural of cv
    [cv-a (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-a.html#cv-a-nn-noun-dMV~64xF) [Norwegian Nynorsk] definite plural of cv
    [cv-ar (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-ar.html#cv-ar-nn-noun-rKD3Sqs2) [Norwegian Nynorsk] indefinite plural of cv
    [cv:ts (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv%3Ats.html#cv%3Ats-sv-noun-Yp-te522) [Swedish] definite genitive singular of cv
    [cv-i (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-i.html#cv-i-nn-noun-dMV~64xF) [Norwegian Nynorsk] definite plural of cv
    [cv:s (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv%3As.html#cv%3As-sv-noun-lV3R1LN-) [Swedish] indefinite genitive singular of cv
    [cv-et (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-et.html#cv-et-nb-noun-wP9ky3UU) [Norwegian Bokmål] definite singular of cv
    [cv-et (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-et.html#cv-et-nn-noun-wP9ky3UU) [Norwegian Nynorsk] definite singular of cv
    [cv-ene (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-ene.html#cv-ene-nb-noun-dMV~64xF) [Norwegian Bokmål] definite plural of cv
    [cv-ane (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-ane.html#cv-ane-nn-noun-dMV~64xF) [Norwegian Nynorsk] definite plural of cv
    [cv-en (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-en.html#cv-en-nb-noun-wP9ky3UU) [Norwegian Bokmål] definite singular of cv
    [cv-en (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv-en.html#cv-en-nn-noun-wP9ky3UU) [Norwegian Nynorsk] definite singular of cv
    [cv:n (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv%3An.html#cv%3An-sv-noun-rKD3Sqs2) [Swedish] indefinite plural of cv
    [cv:t (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv%3At.html#cv%3At-sv-noun-wP9ky3UU) [Swedish] definite singular of cv
    [cv:ns (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv%3Ans.html#cv%3Ans-sv-noun-cMktvohq) [Swedish] indefinite genitive plural of cv
    [cv:na (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv%3Ana.html#cv%3Ana-sv-noun-dMV~64xF) [Swedish] definite plural of cv
    [cv:nas (Noun)](https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/cv/cv%3Anas.html#cv%3Anas-sv-noun-9G0AVOxZ) [Swedish] definite genitive plural of cv
```

**Comment by digitalheir** [comment]
Entry does exist on Wiktionary, but with a different URL.

https://en.wiktionary.org/wiki/Unsupported_titles/cv:s

**Comment by kristian-clausal** [comment]
The data seems to be correct (it's short and to the point), it's just that the link 'back' to Wiktionary is broken, the cv:t syntax does something magical that redirects to incubator.wiktionary.org (which I don't know what it is). The colon apparently requires an `/Unsupported_titles/` special url, while we just smoosh together en.wiktionary.org/wiki/ + article title (with some modifications, like spaces -> _ etc).

Note that this is not part of the data. The URL is just something I added afterwards to the kaikki.org site specifically, it's generated when the site HTML is generated. If you want to use the data, use the data we provide and don't bother scraping the HTML.

The simplest way to get the URL right is to save that information when handling a dump... Although thinking of it, I'm not sure the dump file actually contains the eventual wiktionary.org url. Then the JSON data would actually need to contain the original URL, which in 99.9995% of cases is superfluous and would take up some extra space in the data.

The way to fix this would be to figure out some Wikimedia-specific way to generate the urls from the article titles and replace the simple string manipulation in the kaikki.org html generation code. If anyone knows the algorithm/procedure, please let us know. Otherwise it would kind of just be a snipe hunt for the right solution.

Currently, if users come across wiktionary urls that point to the wrong article they will just have to go through the Wiktionary search function, which is annoying but not breaking. The other solution is to remove the URL altogether, because we currently don't know if we can find a way to guarantee its correctness... That would also help with SEO, by having less broken links on kaikki.org... :speak_no_evil: :see_no_evil: :hear_no_evil:

**Comment by digitalheir** [comment]
In the same category, found this Danish entry which is very hard to get to even from the Wiktionary website (search does not work, you need to click it from the category Danish lemmas by alphabet).

https://kaikki.org/dictionary/Danish/meaning/-/-%60/-%60vert%60%60vert%60-.html

https://en.wiktionary.org/wiki/Unsupported_titles/-%60vert%60%60vert%60-#Danish

Indeed all the data seems to be correct, except in this one "\`vert\`" is not expanded?

I don't know if you want to do anything with it, it is perhaps just a curiosity. I'm impressed that the extractor works so well!

**Comment by xxyzz** [comment]
MediaWiki uses "Unsupported titles" in URL due to technical restriction, one of the limitation is page titles are not allowed to have prefix(letters before a colon): https://en.wiktionary.org/wiki/Appendix:Unsupported_titles, https://meta.wikimedia.org/wiki/Help:Page_name#Restrictions

And [Wikimedia Incubator](https://incubator.wikimedia.org/wiki/Incubator:Main_Page) is for hosting potential new-language Wikimedia project.

**Comment by kristian-clausal** [comment]
https://github.com/tatuylonen/wiktextract/commit/69357b4be41eaeca4b8ac24ef591ed5f45758e21 should fix this.

The page data we get from dumps *does* have `Unsupported titles/` in their title, which is fixed at some point with a separate manually-created unsupported_titles.py

The data now contains an "original_title" field if the title differs from the `word`, which kaikki.org's html generation now uses to generate the URL.

Most "original_title"s should be `Unsupported titles/`, which get a DEBUG message of their own so that we can later update unsupported_titles.py. Other "original_titles" get a debug message of their own, because they shouldn't happen, really. We'll see.

unsupported_titles.py has also been moved to extractor/en/unsupported_titles.py, and other editions should also support something similar in their own Wiktionaries. The debug messages above should be helpful determining these weird URLs.

unsupported_titles.py could and probably should be just a .json file in /data/, but that's a later commit.

**Comment by kristian-clausal** [comment]
Kaikki.org has update and the `Unsupported titles/` urls are now correct.
