### ISSUE TITLE
wrong pronuncation tags extracted

### ISSUE THREAD

**Issue by jhdeov** [tatuylonen/wiktextract#403]
For Armenian, the Wiktionary pronunciation section tends to have at least two pronunciation forms -- Eastern and Western. See for example [սեռ](https://en.wiktionary.org/wiki/%D5%BD%D5%A5%D5%BC) which is Eastern Armenian [sɛr] and Western Armenian [sɛɾ] with different final consonants.

```
Pronunciation
(Eastern Armenian, standard) (IPA): [sɛr]
(Western Armenian, standard) (IPA): [sɛɾ]
```

But on [Kaikki](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D5%BD/%D5%BD%D5%A5/%D5%BD%D5%A5%D5%BC.html), the raw extracted JSON changed the Western Armenian tag to Eastern Armenian. 

```
"sounds": [
    {
      "ipa": "[sɛr]",
      "tags": [
        "Eastern-Armenian",
        "standard"
      ]
    },
    {
      "ipa": "[sɛɾ]",
      "tags": [
        "Eastern-Armenian",
        "standard"
      ]
    },
```

This error seems to be widespread in the kaikki data for Armenian. See for instance the word պատ on [Wiktionary](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D5%BA/%D5%BA%D5%A1/%D5%BA%D5%A1%D5%BF.html) vs [Kaikki](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D5%BA/%D5%BA%D5%A1/%D5%BA%D5%A1%D5%BF.html). The transcription [bɑd] is tagged as Western on wiktionary, but Eastern on Kaikki.

**Comment by kristian-clausal** [comment]
Yeah, definitely seems like there's something wrong going on here. I'm going to take a look at it.

**Comment by kristian-clausal** [comment]
When the `hy-pron` template is expanded, it is expanded so that it just becomes one long line: `* eastern armenian stuff etc. etc [pron]* western armenian stuff [prun]`

The template is actually made out of a one line, unreadable `{{ifeq}}` string, but it doesn't have newlines in its parameters that should generate the list that appears on the article page.

Adding newlines after the `=` in the if-templates doesn't actually work, it's all part of one line anyhow. But even if there were no newlines, this should still be parsed (somehow) as a table, if we go by what happens on the Wiktionary-side.

@xxyzz iirc you might have touched template parameter parsing recently, right?

**Comment by kristian-clausal** [comment]
Nevermind, I tested a really old version of wiktwords and the error is the same there.

**Comment by kristian-clausal** [comment]
It might be this:

https://meta.wikimedia.org/wiki/Help:Newlines_and_spaces#Automatic_newline

Wikitext is such a mess. I'll try to figure out if this is what we already do, attempt to do, or if it's missing.

**Comment by kristian-clausal** [comment]
Closing as fixed.
