### ISSUE TITLE
an alternative form is treated as inflected form

### ISSUE THREAD

**Issue by jhdeov** [tatuylonen/wiktextract#404]
On Wiktionary, the Armenian word [խոսել](https://en.wiktionary.org/wiki/%D5%AD%D5%B8%D5%BD%D5%A5%D5%AC) has the word խօսիլ listed as an alternative form (the last line). 

```
Alternative forms

    խոսալ (xosal) — somewhat colloquial
    խօսիլ (xōsil) — Western Armenian, traditional orthography spelling
```

But on [Kaikki](https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D5%AD/%D5%AD%D5%B8/%D5%AD%D5%B8%D5%BD%D5%A5%D5%AC.html), խօսիլ is listed as an inflected  form.

```
Inflected forms

    խօսիլ (Verb) [Armenian] Western Armenian form of խոսել (xosel)
```

**Comment by kristian-clausal** [comment]
The data seems to be correct (it's been put under "synonyms"), just the website (which is a secondary thing) is being weird. I'll look into it, but this is low-priority because it's the website, not wiktextract itself.

**Comment by kristian-clausal** [comment]
Actually, I think I know what's going on: the inflection information is not taken from the data for https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D5%AD/%D5%AD%D5%B8/%D5%AD%D5%B8%D5%BD%D5%A5%D5%AC.html it is taken from https://kaikki.org/dictionary/All%20languages%20combined/meaning/%D5%AD/%D5%AD%D6%85/%D5%AD%D6%85%D5%BD%D5%AB%D5%AC.html#%D5%AD%D6%85%D5%BD%D5%AB%D5%AC-hy-verb-r1Ah0XAm

Because on https://en.wiktionary.org/wiki/%D5%AD%D6%85%D5%BD%D5%AB%D5%AC we have the sense:

`   1. [Western Armenian](https://en.wikipedia.org/wiki/Western_Armenian) form of [խոսել](https://en.wiktionary.org/wiki/%D5%AD%D5%B8%D5%BD%D5%A5%D5%AC#Armenian) (xosel)`

that creates a link that is interpreted as an inflection because it *looks* like it's that kind of article.

This is a very minor thing, and something that I suspect can't be 'fixed' because there is too much to interpret. How can we know that *this* word that has as its sense "form of" isn't actually an inflection? At best, we can just generalize the section more so that becomes "pages that refer back to here as the 'original' form" section.

Closing, because this is minor enough and annoying enough and possibly *impossible* enough to not be fixable. Might change the section title from "inflection" to something else more general.

**Comment by jhdeov** [comment]
But if the problem is ambiguity for the phrase "form of" for the entry [խօսիլ](https://en.m.wiktionary.org/wiki/խօսիլ) (word A),then how come the entry [խոսալ](https://en.m.wiktionary.org/wiki/խոսալ) (word B) doesn't cause ambiguity. 

Word A [խօսիլ](https://en.m.wiktionary.org/wiki/խօսիլ) is listed as "Western Armenian form of [խոսել](https://en.m.wiktionary.org/wiki/խոսել) (word C)

For [խոսալ](https://en.m.wiktionary.org/wiki/խոսալ) (word B), it's described as "alternative form of [խոսել](https://en.m.wiktionary.org/wiki/խոսել) (word C)". 

Yet on the primary page for [խոսել](https://en.m.wiktionary.org/wiki/խոսել) (word C), the word [խոսալ](https://en.m.wiktionary.org/wiki/խոսալ) (word B) is correctly placed in the alternative form section, while [խօսիլ](https://en.m.wiktionary.org/wiki/խօսիլ) (word A) is an inflected form. 

Does the wiktextract system treat the phrase "alternative form" as a special phrase already? Because then why not make kaikki forcibly copy what's listed as an alternative form on the Wiktionary page for [խոսել](https://en.m.wiktionary.org/wiki/խոսել) (word C) -- which includes the other two words?

**Comment by kristian-clausal** [comment]
This is not wiktextract, it's just the HTML generation for the kaikki.org website. Presumably the data itself is correct. Apparently "alternative form" is enough for it to be slotted correctly on the website (which is not Wiktextract, this is just an extra thing on top). "Western Armenian form of" is ambiguous, and ambiguity will always pop up no matter what we do.

I will reiterate, this is not a Wiktextract issue, it's a Kaikki.org html generation issue. The data is correct (which you can download), and the website is secondary to the data itself.

**Comment by kristian-clausal** [comment]
This is wiktextract and I was wrooong. The kaikki html generator generates the page from a collated list that has data from "form_of" fields, and those are assigned to `Inflected forms`, so it's not a heuristic on the website side, it's that the data of the alternative form has been parsed without an "alternative" tag (which is what probably triggers the difference). There's a taggable text `alternative form` in tags.py that assigns the tag ["alternative"], so what is needed to do is have a kludge somewhere to interpret "[Location or Dialect Name] form of" in the same way, which is going to be mildly annoying to figure out where to slot it, unless I can find a similar piece of code somewhere.

**Comment by kristian-clausal** [comment]
There seems to be no issues with the current state, so I'm closing this.
