### ISSUE TITLE
Download links to all extracted data

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#431]
Thanks to all of you for the valuable work in extracting data from non-English Wiktionaries, it's truly fantastic that there are now multiple parsable editions. I think it would be pretty cool to have easy download links to the extracted data from all editions and possibly add them to the README. 

@xxyzz already hosts the French and Chinese data [here](https://github.com/xxyzz/wiktextract/releases) 👍 (these are only probably not very easy to find if you don't know they exists.)

**Comment by kristian-clausal** [comment]
Oh lol.

This was actually already done yesterday, but the commit to the kaikki repo didn't make it for last night's run! There should be links on the raw downloads page https://kaikki.org/dictionary/rawdata.html by tomorrow, if all goes well.

The README is a good catch.

**Comment by kristian-clausal** [comment]
I see that the other editions "failed to generate", which could mean a lot of things... I'll check it out.

**Comment by kristian-clausal** [comment]
I just had the wrong name for a subfolder (it was the older 'es-edition/' instead of just 'es'). I could have sworn I changed it. Oh well.

The files were generated, but the HTML generation failed the detect the folders by the older name.

*Currently* the files are at
https://kaikki.org/dictionary/downloads/XX-edition/XX-edition-extract.json
https://kaikki.org/dictionary/downloads/XX-edition/XX-edition-extract.errors
https://kaikki.org/dictionary/downloads/XX-edition/XX-edition-extract.log
XX is one of `es`, `zh`, `fr`, `de`, `ru`.

But the links should be fixed by tomorrow, and the above links will be obsolete. But if you really need to take a look, there they are.

**Comment by xxyzz** [comment]
Download links are up and the assert error in Chinese extractor is also fixed, close the issue now.
