### ISSUE TITLE
Incorrect romanizations

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#46]
I noticed a few problems with the romanization of Arabic translations in the latest English dump at https://kaikki.org/:

* Translations of [girl (young female person)](https://en.wiktionary.org/wiki/girl#Translations): romanization of "طِفْلة" is "child", but should be "ṭifla".

* Translations of [woman (adult female person)](https://en.wiktionary.org/wiki/woman/translations#Noun): romanization of "نِسَاء" is "suppletive plural" instead of "nisāʾ".

* Translations of [year (time it takes for the Earth to complete one revolution around the Sun)](https://en.wiktionary.org/wiki/year#Translations): romanization of "عَام" is "plural: أَعْوَام‎ pl (ʾaʿwām)" instead of "ʿām"; "سَنَة" has the same problem.

Other Arabic romanizations have similar problems – in all these cases it seems that a gloss or further information is considered as romanization.

**Comment by tatuylonen** [comment]
This is a broader problem related to parenthesized parts in translations.  They can be romanizations, sense descriptions (often additional detail on the word sense), or linguistic information that should go into the "tags" field.  I don't yet have a generic solution. I'm thinking about a function that would heuristically check whether it looks like tags, and if not, whether it looks like English words (then interpreting as sense), and otherwise interpreting it as a romanization.  I think this approach should work fairly well, but there could be some romanizations that look like english words or tags, so it is not likely to work 100%.  I'd welcome any additional ideas on how to solve this.

**Comment by ChristianSi** [comment]
Hm, do you parse the HTML output or the raw wiki text? In the HTML output, it seems that romanizations are always tagged with `span class="tr Latn"`, while other information is tagged in other ways.

In the wiki text, I notice that ``{{qualifier|...}}`` is used for information such as "child" and "suppletive plural".

**Comment by ChristianSi** [comment]
Unsurprisingly, this also affects romanizations from other languages, e.g. among the Russian translations of "woman", "жена́" becomes "archaic or poetic" instead of "žená". Interestingly, "ба́ба" is correctly transliterated as "bába", though there is also a gloss there ("pejorative").

**Comment by ChristianSi** [comment]
Another challenge are Korean translations, since here alternative spellings are sometimes listed in parentheses. For example, the first translation of "woman" is: 여성 (ko) (yeoseong) (女性 (ko))

Here "女性"  is extracted as romanization instead of "yeoseong".

It will be interesting to see how well your improved extractor can handle such tricky issues.

**Comment by tatuylonen** [comment]
I just committed major changes to translation extraction (web site should update by tomorrow).
  - The Korean issue (yeoseong) seems fixed
  - The Russian issue seems to be fixed
  - The issue with blood/Arabic seems fixed (this required a separate kludge)
  - The issue with girl/Arabic seems to be fixed
  - The issue with year/Arabic seems to be fixed

Thus I think this issue is ready to be closed, unless other issues come up (or I reintroduced some of them after testing).  The website should update with the fixes tonight.  The fixes are mostly generic and should fix numerous related issues.

However there is a heuristic element involved, particularly in differentiating between romanization, "english", and "tags".  There are probably words that aren't handled correctly.  Let me know when you encounter them.  The Enlgish dictionary I'm using for recognizing English words is not complete, but those are easy to fix.

**Comment by tatuylonen** [comment]
Oops, the issue with "year" (plural:) is not yet fixed, working on it.

**Comment by tatuylonen** [comment]
Ok, parsing nested translations (such as those for plural in year/English/Translations/Arabic) should now be implemented and seems to work for at least this word.

**Comment by ChristianSi** [comment]
I can confirm that all these issues are fixed now. Thanks a lot!

I'll take a quit look whether I spot any not-yet-resolved or new issues in this area.

**Comment by ChristianSi** [comment]
All in all this looks really good now, but a found a few romanizations where there
are still problems.

One Arabic romanization of "eighty" (80) is "only nominative".

One Mandarin romanization of "orange" (fruit) is 'but often used as "orange"'.

The Korean romanization of "Australia" (Commonwealth) is "濠州".

The Korean romanization of "my name is" is "casual". There are in fact several translations listed, but it seems that most of them don't have any romanizations extracted at all.

One Russian romanization of "ban" (forbid) is "internet, slang", while "zabánitʹ" is missing. This was actually broken by the recent update; it used to work correctly.

**Comment by tatuylonen** [comment]
- "eighty" fixed (added "only" as a word allowed in tags)
- "orange" fixed the issue you mentioned (added '"' as an allowed character in English)
- "Australia" fixed (check if the second part of parenthesized expression looks like romanization - now this goes in "alt")
- "my name is" fixed (recognize "casual" as an alias for tag "informal")
- "ban" fixed (recognize "internet" as an alias for "Internet")

I started regenerating the website, should be done in about six hours.

**Comment by ChristianSi** [comment]
I can confirm that most of these issues are fixed, except that the Korean romanizations of "Australia" and "my name is" is now missing altogether! (It seems they are treated as tags instead.)

Several Japanese romanization got lost as well with this update. These include

* the first translation of "book" (collection of sheets of paper...) – should be "hon"
* the first translation of "leaf" (part of a plant) – should be "ha"
* the last translation of "new" (recently made or created) – should be "shin"
* the last translation of "Sanskrit" (language) – should be "bongo"
* the translation of "translation" (act of translating...) – should be "hon'yaku"

**Comment by tatuylonen** [comment]
This was due to two separate issues, both of which have now been fixed:
  - the "kanji (XXX, YYY)" syntax did not handle YYY as romanization if it was an English word.  Now single-word english words are accepted as romanizations there.
  - Apostrophe was not accepted in romanizations.  Now it is.

I just committed the changes and they should be reflected on the web site I run the regeneration script (probably tonight).

**Comment by ChristianSi** [comment]
Very good. The Japanese romanizations have all been fixed, thanks a lot!

However, there still seems to be little issue with the Korean romanization of "my name is". It seems they end up in the "alt" field, rather than in the "roman" field where I would expect them.

**Comment by tatuylonen** [comment]
Just fixed the "my name is" Korean romanizations.  The issue was that "." was not an allowed character in romanizations.  Now it and unicode "…" (and a few more accent characters) are permitted.  The fix should be reflected on the web site tomorrow.

**Comment by ChristianSi** [comment]
Yes, the "my name is" issue is fixed now.

However, I notice that the same update introduced the tendency to lose the last word of a translation in certain cases:

* "abhor (to regard with horror or detestation)": one fr translation is now "avoir horreur" instead of "avoir horreur de".
* A final "de" got also lost in the es, fr, pt translations of "aboard (on board of)" and in one pt translation of "about (nearly, approximately)".
* The ms translation of "Croatian (person of Croatia)" is now "orang" instead of "orang Croatia"; likewise, for "Croatian (the standardized variety of Serbo-Croatian)" it's now "bahasa" instead of "bahasa Croatia".

It seems that the missing word is treated as a tag – the translations ending in "de" now have a "tags": ["Germany"] field instead.

Another, possible unrelated issue is that the pt translation of "-est (superlative of adjectives and adverbs)" has changed from "mais used with definite article" to "mais used with". In fact it seems that "mais" is the intended translation and "used with definite article" should be treated as something like a comment, but I'm not sure if the data model can represent that.

Forgive me for mentioning these issues here. They don't concern romanization and hence would warrant a new issue, but since they were introduced by the same update I thought it most simple to mention them here. (Feel free to move them elsewhere if you disagree.)

**Comment by tatuylonen** [comment]
Thanks again for the report!

Abort, aboard, and Croatian should now be fixed.  The bug was that I overextended which tags are accepted as tags at the end of translations.  I now changed it back to accepting the same limited set as are accepted at the end of the head entry.  This may break a few things I already fixed in the last week, but I clearly need to roll back the earlier extension.

The -est issue was caused by the same thing.  However, it is my intention to attempt to eliminate all usage notes from translations (i.e., translations would be only the actual word used in the other language).  Thus I added "used with" to the strings that cause the entry to be skipped.  I'm considering trying to put the usage notes or the full original text in a different field though.  This will result in some words with no translations (but some might have that different field).  There are, for example, quite a lot of translation entries with "+ genitive" or something like that, and many just contain different kinds of usage notes.

Alternatives indicated with / are another matter.  Many of them are ambiguous - without knowing the language I'm often not able to tell whether the alternatives are for a single word or a phrase and a word.  These may need to be edited in Wiktionary.  I'm currently interpreting single-word entries as clear and / surrounded by spaces separating complete phrases.

Then there seem to be quite a few translations of the form "tr1 f tr2 m tr3" or something like that.  I think these should be fixed in Wiktionary to make them unambiguous.

**Comment by tatuylonen** [comment]
I just implemented and commited putting the descriptive translations into a "note" field in translations.  It is now possible to have translations without "word" (or both may be present).  Certain ambiguous or uninterpretable translations may also go in "note".

**Comment by ChristianSi** [comment]
Very good!

**Comment by ChristianSi** [comment]
It seems, though, that you still need to update the format description on the main page ("note" isn't mentioned yet)?
