### ISSUE TITLE
zh edition has insane number of category values

### ISSUE THREAD

**Issue by tatuylonen** [tatuylonen/wiktextract#491]
zh edition seems to have an insane number of categories.  This is causing html generation to crash because there are almost 500000 different files in the directory zhwiktionary/All languages combined/category-words and the operating system is complaining about too many links.

It will be necessary to filter out useless categories.  Examples of patterns generating very many category names include (these are from file names, so some name mangling has been done):

category-Inflections with a red link for singu*
category-Pouye名詞
category-Pouye詞元
category-Q後不接U的英語詞-BBQ'd--Lingqijing (many languages, many word ranges, I assume; this is by far the largest group)
category-來自原始印歐語詞根_star_ǵenh₁-的意第緒語詞
category-日語詞元-貞道--貴方達 (I have no idea what these mean or whether they should be kept - but the pattern seems common)
category-有多餘轉寫的詞_slash_krc-бир--кир
category-派生自原始馬來-波利尼西亞語的伊斯納格語詞 (the pattern looks common, I have no idea whether these should be kept)
category-漢語紅鏈_slash_l-shuāyá--shuōshíhuà
category-烏克蘭語 諜報 (no idea whether this pattern should be kept, but there are many)

**Comment by tatuylonen** [comment]
The filtering of categories can also be done in web site generation, but I would still need to know which patterns should be filtered.

**Comment by xxyzz** [comment]
Some category links do have many pages like [Category:漢語紅鏈](https://zh.wiktionary.org/wiki/Category:漢語紅鏈)(I think this means a page has non-exist link), 63750 lines in the jsonl file has this category. But some other links like "烏克蘭語 諜報"(not exists on Wiktionary, from page [агент](https://zh.wiktionary.org/wiki/агент)), only one line has this category. [Q後不接U的英語](https://zh.wiktionary.org/wiki/Category:Q後不接U的英語詞)(means a English word that doesn't have letter "U" after letter "Q") has 92 lines and all of them are English words so I'm supersized this one could be the largest group and has many languages. I think [日語詞元](https://zh.wiktionary.org/wiki/Category:日語詞元) is for Japanese words, seems fine.

I think most of the category links are valid categories, they should be kept in the JSON file and it's impractical to filter them by patterns. It's difficult to decide which category is useless, all of them seem meaningful... 

I guess the problem is some category links have too many pages but not the jsonl file contains too many different category links? The zh edition has 54001 categories links, here are the top ten: 
category | words 
-------------|------------
朝鲜语 | 191877
世界語非詞元形式 |113276
俄语 |83875
瑞典語非詞元形式 | 83317
日语 | 80347
漢語拼音 | 63896
官話非詞元形式 | 63868
瑞典語名詞變格形 | 59880
法語非詞元形式 | 57792
法語動詞變位形式 | 49487

but the en edition has 133439 categories links and it's top 10 categories have about the same amount of pages as the zh edition...

**Comment by xxyzz** [comment]
fr edition has some translation categories([Catégorie:Traductions en anglais](https://fr.wiktionary.org/wiki/Catégorie:Traductions_en_anglais)), maybe these would be considered "useless"?

**Comment by kristian-clausal** [comment]
If `category-Q後不接U的英語詞-BBQ'd--Lingqijing` is for English words with Q without U after it, something is just wrong with getting the category data: "-BBQ'd--Lingqijing` is added to the end for some reason, which creates gazillions of garbage categories. The extractor is generating categories wrong.

**Comment by xxyzz** [comment]
I'm pretty sure there are no "Q後不接U的英語詞-BBQ'd--Lingqijing" in the JSONL file, only 92 lines have "Q後不接U的英語詞". I guess "category-Q後不接U的英語詞-BBQ'd--Lingqijing" is a HTML file that contains links from word "BBQ'd" to "Lingqijing".

**Comment by kristian-clausal** [comment]
I've just rerun wiktwords with zh to create a db (actually didn't need to do the full run, but oh well...) and tried running wiktextract.categories.extract_categories.py on just that and got a list with only about 4600 lines.

**Comment by tatuylonen** [comment]
Let's hold off a bit before making big changes due to this.  I started this thread when copying files to the web server was showing errors, but now I've seen those errors elsewhere.  I'm actually beginning to suspect I may have hit a Linux kernel bug (some kind race condition in parallel directory operations on large directories on ext4).

**Comment by tatuylonen** [comment]
The problem was actually due to too many subdirectories generated in a directory.  I've fixed this issue by changing the website directory structure for lists (including category lists and its subpages).  The location of word pages has not changed so most existing links should remain valid.
