### ISSUE TITLE
get_all_names() seems to have become a bottle-neck for some reason

### ISSUE THREAD

**Issue by kristian-clausal** [tatuylonen/wiktextract#505]
Wiktextract tests are not stalling, but getting extremely slow in the case of test_long

What we found that there's a regex in pages.py/process_categories that is being generated a lot and the line number 264 was found in the stack trace a lot. Moving this re.compile() call outside of process_categories is tricky because it needs context from wxr.wtp, and then there's opposite in en/page.py where we have a global regex that can't take wxr.wtp.

**Comment by xxyzz** [comment]
`starts_lang_re` could be a global variable because `process_categories` is only used by the English extractor, the "Rhymes" namespace name could be hard coded.

I'll update the mediawiki_langcodes package, my last changes make the `get_all_names` slower when the first argument is passed(all language names are returned). I mistakenly think this function will only be called once because all names are returned.

**Comment by xxyzz** [comment]
[v0.2.1](https://github.com/xxyzz/mediawiki_langcodes/releases/tag/v0.2.1) is released and it the performance is the same as v0.1.2.

But `start_lang_re` should still be changed to a global variable because even though compiled regex objects are cache but the code creating the pattern is still executed for each time when `process_categories` is called.

**Comment by kristian-clausal** [comment]
I wrote some code for that yesterday, but it was late and I came across the regex in en/page.py that was outside the context of wxr.wtp (while start_lang_re needs wxr.wtp). It's just a bit annoying to do. Thanks for optimizing mediawiki_langcodes!

**Comment by kristian-clausal** [comment]
The speed up of test_long is significant, previously it took a couple or even a few minutes, now it was done in under ten seconds!

**Comment by xxyzz** [comment]
`mediawiki_langcodes.get_all_names()` is still slow when the first argument is not an empty string and the second argument is `True`, I guess I could get away with it if this function is not called too many times in this way...
