### ISSUE TITLE
Some Turkish translations missing

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#53]
This is a follow-up to a [comment in #52](https://github.com/tatuylonen/wiktextract/issues/52#issuecomment-845341776), where I'd noticed that two Turkish translations of "woman" – "gacı" and "cıvır", accidentally started with a hat (^). Now the hat is gone, but the translations themselves are missing as well! Looks like one bug was substituted by another...

**Comment by tatuylonen** [comment]
I made some changes today that are related.  Now there seem to be Turkish translations.  However, I am intentionally skipping t+check and t-check templates (these generate the "please verify" text in the translation).  The translations "gacı" and "cıvır" use this template.  The reason for skipping these is that they seem to contain outright garbage in some entries and very varying formatting in others.  Presumably they should be transitory and fixed in Wiktionary at some point anyway.  For the same reasons, I now also ignore translations in the "Translations to be checked" section.  Their formatting is just too inconsistent.  They need to be fixed in Wiktionary (presumably they are gradually being fixed all the time).

This should be reflected on the web site tomorrow (Thursday).

**Comment by ChristianSi** [comment]
Ah, I see, that makes sense.
