### ISSUE TITLE
Compressed complete dictionary file missing

### ISSUE THREAD

**Issue by DanielSWolf** [tatuylonen/wiktextract#54]
I've automated the process of downloading the latest Wiktextract version from https://kaikki.org/dictionary/All%20languages%20combined/kaikki.org-dictionary-all.json.bz2. I just ran this process in order to evaluate the changes from #48, but I got a 404 error. It seems that this file no longer exists.

The uncompressed version is still available. But downloading 4 GB of uncompressed text data takes a while.

Is there any chance of getting back the compressed file?

**Comment by tatuylonen** [comment]
There is now a .gz file instead.  I switched to using HTTP-level compression via the gzip_static option in nginx.

Of course it wouldn't be hard to continue to create the .bz2 file.  If there is a need I could keep doing that.  (Also depends on what the outcome from the other issue you reported is - if it turns out to be an nginx bug, then I may need to stop using gzip_static)

**Comment by DanielSWolf** [comment]
Thanks for your answer! I only just realized that this issue is basically a duplicate of #52. Sorry for that!

Switching from the *.bz2* file to the *.gz* file worked flawlessly for me. It also means that I don't have to worry any more about HTTP-level compression. I'm closing this issue.

Maybe you might want to mention on your website that there are *.gz* versions of all files to prevent people like me from creating superfluous issues. 😉
