### ISSUE TITLE
Some Latin words missing, not sure why

### ISSUE THREAD

**Issue by fpw** [tatuylonen/wiktextract#56]
I noticed that a few words a missing in the Latin JSON, for example: https://en.wiktionary.org/wiki/amica

Amicus is there, but Amica isn't: https://kaikki.org/dictionary/Latin/by-pos/noun/am.html

Could it be due to the superfluous line between Italian and Latin that makes the parser not recognize the Latin entry?

**Comment by tatuylonen** [comment]
I can confirm this but don't yet know what the cause is.  I'm working on it, but it is kind of slow as I can generally run only one or two website regeneration cycles per day.  It looks like the word is also missing from the extracted raw JSON file, but when I extract the page manually, the words are extracted correctly.  (I have not yet verified whether the page is present in the latest dump.)  I'm also having problems with my extraction scripts suddenly hanging, which I'll probably need to resolve first (again the multi-hour test cycle makes it a bit slow).

**Comment by tatuylonen** [comment]
amica/Latin was missing because the page uses an unusual encoding for it - the subtitles on the page are "Noun 1", "Noun 2", etc., and this was not handled properly.  There appear to be hundreds, if not thousands of such cases.

I've now implemented a fix where it ignores numbers after the part-of-speech word.  Words like this should thus now be properly extracted.  The change should be visible on the website tomorrow (unless something goes wrong in the overnight update).

**Comment by fpw** [comment]
Thanks, can confirm it's working now!
