### ISSUE TITLE
Translations missing for "language"

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#59]
I've noticed that the entry for "language" is missing nearly all translations. In the Wiktionary, they are [here](https://en.wiktionary.org/wiki/language/translations), but in the latest dump, there are only 3 translations in the main "translations" object and none whatsoever under "senses".

**Comment by ChristianSi** [comment]
Ping @tatuylonen : Did you find some time to look into this? This is an important word with many translations that would be good to have. It's also a bit worrying, since it hints that other gaps that might conceivably exist in the dump.

**Comment by tatuylonen** [comment]
Sorry I had missed the original email from github about this and hadn't checked issues on the site.

You seem to be correct that they are still missing from yesterday's extraction.  However, now that I test extraction manually on that page, all translations seem to be extracted correctly.  I made changes to translation extraction earlier today (including related to your other bug report), and it now seems possible that those changes also fixed this issue.  However it bothers me a bit that I don't know what the issue actually was.

I'll let the extraction run overnight and check again tomorrow to make sure they are also properly updated on the web site.

**Comment by tatuylonen** [comment]
The issue still exists today.  I'll investigate further.  I'm getting all translations if I extract just that page in my development environment, but they are missing from the full extracftion.  I've been using 1-2 month dump in my development testing, I'll need to start by bringing that up to the same version to see if the problem is due to some change (e.g., in templates or separate translation pages).  Worst case, it could be some weird caching issue in LUA processing or template extraction; those can be very hard to debug.  I currently have no idea how many pages are effected.

**Comment by tatuylonen** [comment]
After updating my dev environment to the latest dump (20210701) I can reproduce this also in my dev environment in a few seconds.  Thus apparently something has changed in the dump.  This is good news and means it is relatively easy to debug - likely to be resolved today.

**Comment by tatuylonen** [comment]
The problem is that translations for "language" have recently been moved to language/translations, and the link on the main page is non-standard, using "See [[language/translations]]" instead of the normal {{see translation subpage|...}}.

Grepping from all pages in Wiktionary, I could not find any other page with a similar pattern.

**Comment by tatuylonen** [comment]
I just committed a fix; it now interprets any link to a /translations subpage inside the Translations section as importing
translations for the current part-of-speech.  As said, I'm not able to find any other page than "translations" that is like
this.  The fix should make extraction more robust, so I think it is worth keeping even though the issue can (and probably should)
be fixed in Wiktionary by using the normal template.

I just started regenerating the website, and unless something goes wrong the fix should be reflected there in about five hours.

**Comment by ChristianSi** [comment]
Ah, so that was an inconsistency in the data formatting, interesting! I've now fixed the Wiktionary page to use the standard template, but it's certainly good that you have made the extractor more robust.

**Comment by ChristianSi** [comment]
I just got the latest dump and can confirm this is fixed now!

However, with the same update the entry [human being](https://en.wiktionary.org/wiki/human_being) seems to have disappeared. (Or maybe just its translations, but I cannot even find the entry itself.) Possible that is unrelated, but it seems suspicious that it happened with the same update and it seems certainly a bug.

So I'll leave this issue open for now, hoping you'll find the time to look into that as well.

**Comment by tatuylonen** [comment]
"human being" is missing because there was a Python crash on that page during extraction.  The code path to it comes through the kludge I implemented today for /translation links; looks like the code gets executed more often than I intended.  I'll look into this tomorrow.

There were also 2000 other crashes due to another bug that I just fixed; those led to other missing pages.  I just restarted the site generation run, but it won't fix the "human being" issue yet.

**Comment by tatuylonen** [comment]
I just fixed the issue with "human being".  The web site should update in about five hours.

**Comment by ChristianSi** [comment]
"Human being" has reappeared, so I'm closing this.

A general proposal, though: maybe it would make sense not the publish the results of a generation run if there were crashes? (Or if the crash count surpasses a certain small number, say 10 or so.) In that way, sometimes it might take some more hours or days until an update appears – but entries would no longer disappear unexpectedly.
