### ISSUE TITLE
Template expansion

### ISSUE THREAD

**Issue by ZanSara** [tatuylonen/wiktextract#6]
As far as I can see, the current version does not expand templates. For example, once I parse the dump file with `wiktwords enwiktionary-latest-pages-articles.xml.bz2 --out wikt.words --language English --all`, the following snippet:
```
import json
with open("wikt.words") as json_file:
    lines = json_file.readlines()
    for line in lines:
        data = json.loads(line)
        if "conjugation" in data:
            print(data["conjugation"])
            break
```
returns:
```
[{'template_name': 'en-conj-simple'}]
```
Is there any way to get the content of the template instead of its name?

**Comment by FurkanGozukara** [comment]
I am also looking for a way to parse templates. Perhaps wiktionary provides an api? this is the biggest hindrance for me so far

**Comment by erolm-a** [comment]
Hi. I am writing here because I've been working on the very same thing too (English only). I am sorry to rebump this issue but I am working on the very same thing and would be happy to contribute.

The challenge is that there are quite an impressive number of templates. The way they are parsed is not exactly trivial. The dump does not contain the expanded templates but only the roots (for example, `{{en-verb}}` etc.). You may have more luck taking the wiktionary module that does this expansion you are interested in and translating it into the language or framework you are using. For example, [here](https://en.wiktionary.org/wiki/Module:en-headword) is the source code for the main English templates.

I guess in the next few days I'll publish my Python converter. It should be pretty easy to integrate to this script.

By the way this is an amazing script, keep up the good work!

**Comment by yolpsoftware** [comment]
I think Tatu Ylonen (the creator of wiktextract) is working on a new version which runs the templates itself. Not sure about the current status though.

**Comment by erolm-a** [comment]
Oh, funny. I wrote some of them myself. I am not familiar with the code base, and am working with PySpark for a different purpose.

But [here they are](https://gist.github.com/erolm-a/983c698872844f93e43d0fef8d870364). At the moment of writing it only includes noun, adjective and verb extraction but it should be pretty easy to include it into the project.

**Comment by tatuylonen** [comment]
I've implemented the extraction very differently for the new version.  It now expands the templates and executes Lua code, which enables it to handle most things automatically (and is much more future-proof).

As part of the work, I wrote a generic package for processing Wikimedia dump files and processing WIkitext.  It can expand arbitrary templates as well as execute Lua modules.  See [https://github.com/tatuylonen/wikitextprocessor/](https://github.com/tatuylonen/wikitextprocessor/).

**Comment by FurkanGozukara** [comment]
What is the output your parser generates? can you post example output
screenshot or file?

**Comment by tatuylonen** [comment]
Easiest way to look at the output right now is to go to https://kaikki.org/dictionary and download one of the pre-extracted files (there are files for the whole data, individual languages, various word lists, and individual words).  I'll be updating the documentation over the weekend as well in preparation for the 2.0.0 release.
