### ISSUE TITLE
Canonical form for Czech 'pro' contains grammar note

### ISSUE THREAD

**Issue by StefanVukovic99** [tatuylonen/wiktextract#667]
https://en.wiktionary.org/wiki/pro#Czech
![image](https://github.com/tatuylonen/wiktextract/assets/24891609/be3ad10d-8790-4b23-9f2f-9eea8e0c2515)
![image](https://github.com/tatuylonen/wiktextract/assets/24891609/3c3951a4-0a80-4fb7-afe6-c1efc266f198)
![image](https://github.com/tatuylonen/wiktextract/assets/24891609/03449732-0d7a-41b6-a018-9bb000c3616c)

(downstream: https://github.com/themoeway/kaikki-to-yomitan/issues/60)

**Comment by kristian-clausal** [comment]
Oof, this is from a template `Template:+obj`, which is so vague that it's used a bit in all sorts of places. Usually, I'd just leave the output alone in stuff like glosses, but in forms, yeah... Going to be mildly annoying, because there are so many other kludges in that space of the code already.

**Comment by kristian-clausal** [comment]
I've a PR draft up handling this specific thing. Tatu green-lighted adding a new field to the en output, which I'm tentatively calling "coincidence" (because it's about coincident things and terms, because the template is so vague).

The name was a coincidence. I looked for synonyms, saw "coincident", though that was perfect, and didn't realize until later that "coincidence" will be read as "coincidence", not as "coincidence" most of the time.

**Comment by kristian-clausal** [comment]
We're not going to do a kludge for just this template, but make something a bit more generalizable, similar to `etym_templates` instead.

**Comment by xxyzz** [comment]
Fixed in #687
