### ISSUE TITLE
A way to download all/specified Wiktionary Lua modules? 

### ISSUE THREAD

**Issue by twardoch** [tatuylonen/wiktextract#68]
The Wiktra project is a bit related to yours: https://github.com/kbatsuren/wiktra and also has some ways to run Lua code within Python. 

Currently, Wiktra includes old versions of Wiktionary’s transliteration modules. I’ve opened an issue there: https://github.com/kbatsuren/wiktra/issues/5

Could you advise on a method to "extract" the Lua modules from Wiktionary, so the local copies stored in e.g. https://github.com/kbatsuren/wiktra/tree/master/wikt/translit can be updated?

**Comment by twardoch** [comment]
OK, I see that I can do https://en.wiktionary.org/w/index.php?title=Module:scripts&action=raw

**Comment by tatuylonen** [comment]
You can use the --pages-dir option to wiktextract to modules.  For example, if you use "--pages-dir pages", it will create directory "pages/Modules", which contains all the Lua modules.  I use this option frequently (for extracting individual pages), as I can then use the --page option to process any single page for testing.

**Comment by tatuylonen** [comment]
If there is a more general need for the modules, I could easily make them available on https://kaikki.org as a tar file or as individual files, which could be updated whenever a new wiktionary is extracted.  There seem to be about 57000 files under Modules.

**Comment by tatuylonen** [comment]
I just implemented --modules-file and --templates-file options in wiktwords.  If they are specified (with a .tar file name), then modules or templates will be extracted to the respective file.  I'm going to add them to the files that are available for download on kaikki.org.  They should then update every time I regenerate the website, which currently done manually every 1-10 days, but I'm going to fully automate it as soon as the extraction code is stable.  The website generation already always fetches the latest wiktionary dump that is available.

Note that it currently determines what to include based on the namespace.  Thus, /documentation pages are included in the modules file.  Also, it adds .txt at the end of each file.  Some suffix is needed, because Wiktionary can have a module and a directory with the same name.  It also does a few substitutions on the title in order to prevent some dangerous file paths that could pose security risks.

There seem to be about 57000 extracted files under Module (including 2000 documentation files) and 51000 under Template (including about 10000 documentation files).  (These were counted on my desktop which still uses a couple of months old dump file)

**Comment by tatuylonen** [comment]
All Lua modules and templates from Wiktionary are now extracted with the rest of the data and can be downloaded from https://kaikki.org/dictionary/rawdata.html.  They are updated every time the pre-extracted data is regenerated (usually every few days and I'll fully automate it later).

**Comment by twardoch** [comment]
Thanks, this is helpful!
