### ISSUE TITLE
AttributeError: module 'os' has no attribute 'pread'

### ISSUE THREAD

**Issue by kbatsuren** [tatuylonen/wiktextract#71]
`C:\ProgramData\Miniconda3\Scripts\wiktwords.py --all --language Hungarian --out data.json "raw\enwiktionary-20210501-pages-articles-multistream.xml"`

When I run the above command line, it throws the following error.

```
Analyzing which templates should be expanded before parsing
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\Scripts\wiktwords.py", line 228, in <module>
    parse_wiktionary(ctx, args.path, config, word_cb, capture_cb,
  File "C:\ProgramData\Miniconda3\lib\site-packages\wiktextract\wiktionary.py", line 178, in parse_wiktionary
    for ret, stats in ctx.process(path, page_cb, phase1_only=phase1_only):
  File "C:\ProgramData\Miniconda3\lib\site-packages\wikitextprocessor\core.py", line 1255, in reprocess
    success, ret = phase2_page_handler((model, title))
  File "C:\ProgramData\Miniconda3\lib\site-packages\wikitextprocessor\core.py", line 49, in phase2_page_handler
    data = ctx.read_by_title(title)
  File "C:\ProgramData\Miniconda3\lib\site-packages\wikitextprocessor\core.py", line 1317, in read_by_title
    rawdata = os.pread(self.tmp_file.fileno(), page_size, ofs)
AttributeError: module 'os' has no attribute 'pread'
```

Does anyone know how to fix this issue?

Thank you very much for the help.

**Comment by tatuylonen** [comment]
os.pread() was introduced in Python 3.3.  Which version of Python are you using?  Wiktextraxt lists Python 3.6 as minimum (though I don't immediately remember if there was something it needed that was introduced in 3.6).

Another possibility would be that Python on Windows does not have pread (perhaps Windows does not have the pread() system call).  I don't have a Windows machine so I can't test it myself.

Wiktextract uses pread on Linux (instead of lseek() + read()) because as the code is written, when running using multiple processes on Linux the same open file descriptor gets shared among many parallel processes and lseek()+read() would be unreliable (due to a race condition).

However wiktextract does not really support parallel processing on Windows so perhaps I might add some compatibility code that implements pread() using lseek() + read() if it doesn't exist in "os".  That said, running it in single-threaded mode is slow and it could take days to even a week or two to extract the full dataset (whereas it is 1.5 hours on my 128-core Linux server).

One option is also to just use the pre-extracted datasets.  See https://kaikki.org.

**Comment by kbatsuren** [comment]
My python version is 3.8.5. Thank you very much for the quick reply. Okay, I also have a Linux server, so I can play with that. I am closing this issue. Thanks again.
