### ISSUE TITLE
Languages that aren't

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#73]
There are various translations in the English dump whose "lang" field is set to a value that's clearly NOT a language. The boundaries between what should and what shouldn't be considered a language can be hard to draw, but here are various cases where I'm pretty sure that something is amiss – whether in the raw data or in the parsing process I cannot say.

Cases where "lang" actually seems to specify a variety include:

* Ancient
* Classical
* Literary
* Lower
* Modern
* Modified traditional
* Northern
* Northern and Southern
* Simplified
* Southern
* Traditional
* Upper
* Western

Cases where it seems to specify a country or region:

* Alsace
* Bavaria
* Belgium
* Canada
* Central
* Cologne
* Eastern
* Fogo
* Föhr
* Föhr-Amrum
* Hallig
* Helgoland
* Santiago
* Sylt
* Vancouver Island

Cases where it seems to specify a script or writing system:

* Adlam
* ALUPEC
* Carakan
* CJKV Characters
* Cyrillic
* Devanagari
* Glagolitic
* Gurmukhi
* Jawi
* Roman
* Shahmukhi
* Taraškievica
* Uyghurjin

Oddities:

* Iron
* I used to eat cheese - literary
* used with the imperative form of sofa

These lists are not meant to be complete – they just include various cases that caught my attention. Some of these "lang" values may occur only once, others appear various times.

All of them seem to be new in this field – they did only show up during one of the latest dumps made in August.

**Comment by tatuylonen** [comment]
This was a bug caused by recent code refactoring where I moved most of the translation parsing code to a separate file.  The language name was not correctly passed from the parent item to sub-items.  This should now be fixed (though I didn't test extensively).  I also defined some of the terms you listed as specifically recognized as going into tags and added a few tests.  I started the extraction and site regeneration run, so please let me know if you still notice these tomorrow.

**Comment by ChristianSi** [comment]
Yes, looks like these are parsed correctly now.
