### ISSUE TITLE
Some erroneous categories

### ISSUE THREAD

**Issue by yolpsoftware** [tatuylonen/wiktextract#75]
In the current data on https://kaikki.org/dictionary/English/index.html, there are a couple of problematic category associations:

* `lane` is in the category `Cervids`. This is probably because `lane` is in `sh:Cervids` on Wiktionary because `lane` means `fawn` in Serbo-Croatian, but in English there is no association to an animal.
* Probably related: `lane` is in the category `Baby animals`.
* `bat` is not in the category `Bats`, even though it is in `en:Bats` on Wiktionary.
* `tatouay` is not in the category `Armadillos`, even though it is in `en:Armadillos` on Wiktionary.
* `nycterid` is not in `Bats`, even though it is in `en:Bats` on Wiktionary.

**Comment by tatuylonen** [comment]
I currently remove the language prefix from categories.  I welcome opinions as to whether this is the right approach - I could also easily change it to leave the language prefix.

A broader issue is that categories are often specified at the end of the page.  Thus it is often not possible to know which etymology, word sense, or even language they refer to based on the page structure alone.  Furthermore, the language prefixes in category links don't always match the language they really refer to - for example, "A4" has category "en:Paper sizes", even though the paper size sense is under Translingual.

I'm inclined to change the extraction so that I would leave the language prefix in category links and let downstream tools remove the prefix if appropriate for the application.  I'm also not planning to attempt disambiguating them in wiktextract; however, I am planning to disambiguate them in the post-processing for but others might want to implement different disambiguation approaches.

Note that I also remove the vast majority of category links - generally stuff that is not relevant for semantics.  It would be easy to leave also those category links, but it would increase the number of category links extracted by a factor of 3-10.  The list of currently ignored links can be found in wiktextract/page.py:ignored_category_patterns.  Please let me know if you think it would be better to extract all links and leave filtering to downstream tools.

**Comment by yolpsoftware** [comment]
> I'm inclined to change the extraction so that I would leave the language prefix in category links and let downstream tools remove the prefix if appropriate for the application.

I second that. Since the category names are always in English, regardless of the respective language (e.g. `sh:Cervids`), it would be easy to merge them by removing the prefix. And if you put the two categories `sh:Cervids` and `Cervids` together, it would mean that `lane` stays in the category `Cervids`, which would make the categories pretty useless.

As for the category links, I think there are some excluded categories that might be interesting for some usecases:
* nouns, verbs, prepositions ==> these are obviously interesting categories, but we can read the part-of-speech from the senses, so we do not need the categories.
* suffixes, prefixes, acronyms, phrases ==> is that information somewhere in the data? For example, if I want a list of all acronyms, can I extract that?

But I think the `ignored_category_patterns` do not explain the missing categories in `bat`, `tatouay` and `nycterid`. Is that a bug?

**Comment by tatuylonen** [comment]
I just committed two changes related to this:
  - wiktextract no longer filters the categories (any filtering is moved to downstream applications/post-processing)
  - it no longer removes the language prefix from links.
These changes should be reflected on kaikki.org next time I update the database (probably by Monday).

**Comment by tatuylonen** [comment]
I just implemented extracting the category tree using the --categories-file option to wiktwords.  Categories are extracted into a JSON file that contains a dictionary with the keys "roots" and "nodes".  "Fundamental" is the normal root node, and other roots are nodes that are not referenced from any other node.  "nodes" contains a dictionary mapping lowercased category names to dictionaries with the fields "name" (non-lowercased name), "desc" (description of category), "clean_desc" (description cleaned to human-readable text, except {{{langname}}} is left in place), "sort" is list of sorts listed in child nodes, and "children" is list of child node names (note they may need to be lowercased before looking up the child node).

I will make the pre-extracted category tree data available at https://kaikki.org/dictionary/rawdata.html (I expect it to be available by Monday, unless something goes wrong with the updates over the weekend).
