### ISSUE TITLE
Erroneous inflection: "Harrier" -> "thumbHarrier"

### ISSUE THREAD

**Issue by Ian-07** [tatuylonen/wiktextract#910]
wiktextract appears to have taken the "thumb" from the preceding image markup which it then concatenated with the original word:

From [Harrier](https://en.wiktionary.org/wiki/Harrier) on Wiktionary:
```
===Noun===
[[file:Harrier tricolour.jpg|A Harrier dog breed.|thumb]]

{{en-noun}}

# A [[medium-sized#Adjective|medium-sized]] [[dog#Noun|dog]] [[breed#Noun|breed]] of the [[hound#Noun|hound]] [[class#Noun|class]], used for {{l|en|hunting|id=animals}} [[hare#Noun|hares]] by [[trai#Verb|trailing]] them.
```

From [Harrier](https://kaikki.org/dictionary/All%20languages%20combined/meaning/H/Ha/Harrier.html) on kaikki.org:
```
  "forms": [
    {
      "form": "thumbHarrier",
      "tags": [
        "canonical"
      ]
    },
    {
      "form": "Harriers",
      "tags": [
        "plural"
      ]
    }
  ],
```

**Comment by xxyzz** [comment]
`clean_node` returns empty string for this link node, it's not the link regex in `clean_value` this time...

**Comment by kristian-clausal** [comment]
It's not in `parse_word_head`... I'll look into this, this is weird.

**Comment by kristian-clausal** [comment]
Should be fixed with this. The issue was in that we would handle En edition headers with nodes instead of using clean_value. There was a part where we filtered away templates that create floating divs, which was a perfect place to add some more conditions that also remove LINK nodes whose first `largs` argument starts with `file`.
