### ISSUE TITLE
Categories on sense-level vs. on the whole item

### ISSUE THREAD

**Issue by yolpsoftware** [tatuylonen/wiktextract#93]
Hello Tatu

It seems you have somehow managed to assign categories to senses, for example:

https://en.wiktionary.org/wiki/rana#Italian
https://kaikki.org/dictionary/Italian/meaning/r/ra/rana.html#rana-it-noun-dPpTJ8wP

"Rana" in Italian means "frog", but also "breaststroke" in the context of swimming. The Wiktionary article is therefore assigned to the categories "it:Amphibians" and "it:Swimming".

However, in the Wiktextract results, it seems that the two categories are correctly assigned to the relevant sense only.

(hooray! :-) how did you do that? :-O )

Do you have an estimate in how many cases this assignment is correct? In other words, how much can we count on the categories to be assigned to only the relevant senses?

**Comment by yolpsoftware** [comment]
Seems it does not always work:

https://kaikki.org/dictionary/English/meaning/f/fr/frog.html

In the first "noun" section, the fifth entry is

> An organ on the bottom of a horse’s hoof that assists in the circulation of blood.

and in the second section, the first entry is

> (offensive) A French person.

The category "Horses" should not be applied to the "French person" sense, but to the horse topic above.

**Comment by tatuylonen** [comment]
The category disambiguation is currently very experimental.  You can also download the raw data that does not contain the disambiguation from https://kaikki.org/dictionary/rawdata.html.

The current disambiguations seem to be about 75% correct across languages (among words that have two or more senses that need to be disambiguated - since this doesn't count cases where there was only one possible sense, the actual percentage of correct categorizations is significantly higher).  We manually annotated a random sample of about 1000 ambiguous cases and the analysis against that sample is automatically generated at https://kaikki.org/dictionary/errors/dis_evaluation_categories.html every time the website is regenerated.

I'm still undecided about whether to keep the category disambiguation (it needs more work) or whether to disable it entirely.  In any case, the code that does that still needs more work.
