### ISSUE TITLE
Entries from the Reconstruction namespace

### ISSUE THREAD

**Issue by danmysak** [tatuylonen/wiktextract#95]
If I didn’t miss anything, entries from the Reconstruction namespace (like https://en.wiktionary.org/wiki/Reconstruction:Proto-Germanic/kr%C4%93%C7%AD) are not in the extracted data, although some related data is:

```
{"title": "Reconstruction:Proto-Germanic/krāwō", "redirect": "Reconstruction:Proto-Germanic/krēǭ"}
```

Would it be possible to extract those entries too?

Anyway, thanks for the awesome tool!

**Comment by tatuylonen** [comment]
It's on my TODO list.  I'll probably address it within a month or so.  The changes needed should be fairly minor.

**Comment by tatuylonen** [comment]
Since this was not particularly complex, I ended implementing it today.  I just committed the changes.  Unless something goes wrong during my overnight extraction run, the Reconstruction namespace should be included in the data on https://kaikki.org tomorrow.  Reconstructed words are marked with the "reconstruction" tag in the data.  (Some of the changes were in the https://github.com/tatuylonen/wikitextprocessor package so that also needs to be updated if running the extraction on your own machine.)

Please let me know if you notice any errors in the extracted reconstructions.

**Comment by danmysak** [comment]
Excellent! The data seems fine so far, thank you.

**Comment by danmysak** [comment]
@tatuylonen What I did notice just now is that if a reconstructed word contains parentheses, as in [degut(j)as](https://en.wiktionary.org/wiki/Reconstruction:Proto-Balto-Slavic/degut(j)as), than what is inside the parentheses will become "romanization":

```
{
  "senses": [
    {
      "raw_glosses": [
        "tar"
      ],
      "glosses": [
        "tar"
      ],
      "tags": [
        "reconstruction"
      ],
      "categories": [
        "Proto-Balto-Slavic lemmas",
        "Proto-Balto-Slavic masculine nouns",
        "Proto-Balto-Slavic nouns"
      ]
    }
  ],
  "pos": "noun",
  "head_templates": [
    {
      "name": "head",
      "args": {
        "1": "ine-bsl-pro",
        "2": "noun",
        "cat2": "",
        "sort": "",
        "head": "",
        "g": "m",
        "g2": "",
        "g3": ""
      },
      "expansion": "*degut(j)as m"
    }
  ],
  "forms": [
    {
      "form": "degutas",
      "tags": [
        "canonical",
        "masculine"
      ]
    },
    {
      "form": "j",
      "tags": [
        "romanization"
      ]
    }
  ],
  "etymology_text": "",
  "etymology_templates": [],
  "word": "degut(j)as",
  "lang": "Proto-Balto-Slavic",
  "lang_code": "ine-bsl-pro"
}
```
